### ISSUE TITLE
Preview pane not using Visual Studios color theme

### ISSUE THREAD

**Issue by teebee76** [jzoss/Git-Source-Control-Provider#1]
Reposting issue here mainly to test the issue functionality but also to get a better notification of the issues status, I hope you don't mind.

Like I said earlier not a big issue, but if you change the Color-theme of your visual studio everything except the preview pane changes color. It is not a big difference between the Light and the Blue color theme, but if you use the Dark Theme (like I do) the contrast is very big. When working in a dark environment the preview-pane can be very dominant with its bright colors. 

Hope this is an easy fix.

I will post a couple of photos as well.

![image](https://cloud.githubusercontent.com/assets/5390116/11029651/a84b16d8-86c8-11e5-8a9a-53c8e8429890.png)

![image](https://cloud.githubusercontent.com/assets/5390116/11029661/bf491740-86c8-11e5-8028-e0a2355c372e.png)

**Comment by jzoss** [comment]
I totally don't mind , So it looks like just the text editor that the theme is not working.. Photos help a lot thanks. I'm not sure how hard it will be to fix.. but I am guessing it's not too bad. There is a file in the resource directory call Patch-Mode.xshd..  This hold all the values for the editor for syntax highlighting and whatnot.. I will need to copy that and make the colors work for the dark them.. Then I will have to detect what them is being using and load the correct file in the SetDiffCodeHightlighter function in the PendingChangesView.xmal.cs

**Comment by PureKrome** [comment]
Now that #2 is fixed, I can see the preview pane :) I can also confirm that this is _exactly_ like the pic, above. :/

**Comment by jzoss** [comment]
@teebee76 @PureKrome .. Skipped lunch today, for what I thought would be a quick patch.. took me a bit longer than I wanted.. Anyway, thanks for your help.. check out the new 1.4.2 Beta 2 release :)

**Comment by PureKrome** [comment]
@jzoss installing beta 2 now...

**Comment by teebee76** [comment]
Installing... , btw Love the title of the release  :-D 
thanks

**Comment by teebee76** [comment]
Looks better, but not perfect ;) 

This is ofcourse not a big issue, and I don't mind if I have to wait until summer to get it adjusted further.

To better Illustrate I'll include a screenshot
![image](https://cloud.githubusercontent.com/assets/5390116/11624337/6f6d9126-9cd3-11e5-87be-9b5d62b8f367.png)

first off, I like the colors very much, but some adjustments recommandations
* it's hard to read black diff and index on the grey background at the top
* the background for the window is dark grey,but for the text it's pitch black, looks kinda weird. 

since the colors work so well against the pitch-black, I created a mock up with a little Gimp-magic 
and with only 2 changes it looks much better :)

![image](https://cloud.githubusercontent.com/assets/5390116/11624836/d62052fc-9cd6-11e5-8a20-4039dc94a39c.png)

my suggestion would be:
change the background of the window to total blackness and the "diff" and "index" keywords in the top to something other than black (white which I used in the pic may not be the best choice, but works well enough)

**Comment by jzoss** [comment]
@teebee76 - No problem.. .now that I have it switching colors based on theme.. took me like 30 secs to make the switch .. Try in now in 1.4.2 Beta 3..

**Comment by teebee76** [comment]
2 words :) 

Perfect  and Thanks :+1:

**Comment by PureKrome** [comment]
Is this fix in 1.4.2 _release_ ?

I'm on 1.4.2 _release_ and my diff window is still background-white. do i need to reset some setting?

**Comment by teebee76** [comment]
I guess so, I downloaded 1.4.2 restartet vs and this is how it looks

![image](https://cloud.githubusercontent.com/assets/5390116/11655112/3717994c-9dab-11e5-9803-0fccddb4fea9.png)

**Comment by jzoss** [comment]
@PureKrome  Yea it should be all dark, if you are using the dark theme.

**Comment by teebee76** [comment]
@PureKrome I noticed that if I change the theme, the windows does not update it's colors until you restart VisualStudio.

So if you are in dark theme and switch to light or blue, it will remain black until the next time you start VS and vice versa. It does not help to hide and show the pending changes window, at least not for me

**Comment by jzoss** [comment]
@teebee76  You found my hidden, and totally too lazy to fix bug :) I cache the theme when you load the pending changes window.. and I don't load it again until it restarts. This was not an issue until I added a 2nd theme. I knew about it and decided to no fix it now.. because I was not sure how to fix it :) I thought it was better to get one out that work 99% of the time.

**Comment by PureKrome** [comment]
Restarting VS didn't help. I actually had to change my theme THEN restart.

meh - it's-a-workin.

![](http://i.giphy.com/j5IdWWOAYzcli.gif)

**Comment by jzoss** [comment]
@PureKrome Sorry :) I know.. I know.. I need to add a watcher to detect the theme change. :)

**Comment by jzoss** [comment]
@teebee76  + @PureKrome .. I must apologize a lunch I looked at it.. and found in VS 2015 it's pretty easy to fix.. so I did.. it will be in the next release.

**Comment by teebee76** [comment]
I'd consider it a pretty unimportant bug, If users are to lazy to restart VS to make it work, they should try writing their own plugin. At least when it comes to changing something like a theme which I suppose is done pretty seldom. I know of many other applications that require a restart to change things like this.

but hey, now that you actually spent time fixing it, great :)

**Comment by PureKrome** [comment]
@teebee76 it wasn't about restarting VS. it was about having to manually switch the theme back and forth, again.

**Comment by jzoss** [comment]
@teebee76 yea I only fixed it because I was looking at a completely different code example .. Not related to this and there it was.. The fix.. Anyway how else has it be running? Any issues.. A guy on the plugin site said it was causing vs to freeze.. But I have not had any issues

**Comment by PureKrome** [comment]
so far it's been working fine for me.... :) :+1:

**Comment by teebee76** [comment]
first off @PureKrome sorry if I sounded rude, it was never my intention to imply that you were lazy for not restarting or complaining about it. I was just thinking that there are probably more important things to fix, and that if users having too restart, or change theme manually and restart, when they want to switch a theme, fixes the problem, it would not be worth the time fixing it :) 
..-but luckily it was an easy quick fix, so yay for that! ... and it will probably save users from falsly reporting bugs about theme-colors, because they don't see the change right away.

When it comes to freezing, I haven't noticed any of that, at least not yet. Everything here is lightning fast :) 
Will report back of any mysterious behavior I encounter.

**Comment by PureKrome** [comment]
@teebee76 np - i didn't think you were being rude. What i was trying to say was that i had to change the theme (which is easy and 1 sec to do) but I would never have _known_ to do that - there's no suggestion or clue or discoverability. Only by reading this thread did I realise i shoudl try that.

I did what _everyone_ (i guess) would have done -> restart 1x 2x or multi-times (side note: it amazes me how people thing doing 2+ restarts thinks that it might fix the problem. cause yeah ... 3 restarts fixes a problem which 1 restart doesn't fix ... if it _could_ fix it) and the problem wasn't fixed.

all good  though!

**Comment by jzoss** [comment]
@teebee76 and @PureKrome you guys both rock in my book. My biggest annoyance is I wish there was a better place to have discussions on githib :) Anyway.. I did not have much time to do anything today.. This project has been my I'm stuck in a meeting project .. But I did get a little time.. Setup a build.. If you guys want to you can get the latest build from here and test the theme.. Anyway next is to make the whole thing faster.. https://ci.appveyor.com/project/jzoss/git-source-control-provider
