### ISSUE TITLE
1.8.0 doesn't work in VS2017 15.7.2

### ISSUE THREAD

**Issue by waclaw66** [jzoss/Git-Source-Control-Provider#101]
Hi.
After update to 1.8.0 it only shows "Add to source control" in status bar.
1.7.4 works ok.

Regards
Vaclav

**Comment by jzoss** [comment]
@waclaw66 I have not been able to recreate it.. But I took a guess.. 

can you try this build.. https://github.com/jzoss/Git-Source-Control-Provider/releases/tag/GSCP-CI

**Comment by jzoss** [comment]
Fixed 1.8.1
