### ISSUE TITLE
New files in .NET Standard projects not automatically added to source control

### ISSUE THREAD

**Issue by ddobrev** [jzoss/Git-Source-Control-Provider#102]
The feature about automatically adding new, and renamed, files to source control works flawlessly for the old project types. .NET Standard projects, however, use a different format which does not list the contained files. This causes new files added to such projects not to be also added to source control.

**Comment by ddobrev** [comment]
@jzoss please take my insistence as a compliment to your great work: could you please comment on this issue?

**Comment by jzoss** [comment]
Oh hey.. yeah.. I'll take a look. Sorry I've been busy the last few days. I
haven't had a chance to debug it yet..

**Comment by jzoss** [comment]
I see the issue.. just not sure how to fix it yet..

**Comment by ddobrev** [comment]
I can imagine it's difficult, these projects are quite unusual compared to the old ones. Still, I don't think but rather I know you can do it.

**Comment by jzoss** [comment]
Ha.. 2 months ago.. My wife had a baby 😁. No I'm planning on getting back
to working on it.

**Comment by ddobrev** [comment]
@jzoss congratulations! Great programmers such as yourself should definitely reproduce. :) I wish you extreme happiness with all your children, current and future.
