### ISSUE TITLE
Certain types of files not auto-added to source control when included in a project

### ISSUE THREAD

**Issue by ddobrev** [jzoss/Git-Source-Control-Provider#105]
An example is https://github.com/CrossGeeks/AzurePushNotificationPlugin/blob/master/samples/AzurePushNotificationSample/AzurePushNotificationSample.Android/google-services.json .

**Comment by ddobrev** [comment]
@jzoss auto-addition also fails for .NET Standard 2.0 projects, XML files (vector drawables) in Xamarin.Android projects and asset catalogues in Xamarin.iOS projects. The first one is by far the most unpleasant because added files are (incorrectly) marked as added and I often forget to add them manually which leads to ruined commits and team members unable to build. Please comment whether you think you might have the chance to work on this.

**Comment by jzoss** [comment]
@ddobrev -- Ok I think I got it.. Can you try this release and tell me what you think. https://github.com/jzoss/Git-Source-Control-Provider/releases/download/GSCP-CI/GitSccProvider.vsix

**Comment by ddobrev** [comment]
@jzoss .NET Standard and XML in Xamarin.Android both work just fine - thank you! This includes Xamarin.Forms pages which consist of two files, XAML and C# - both are added. Xamarin.iOS assets still don't work but as the state of the plug-in is now much better than it was, I strongly recommend an official release. The assets are rarely used so you deal with them whenever.

**Comment by jzoss** [comment]
Thanks @ddobrev
