### ISSUE TITLE
Multiple Project Source Control Issue

### ISSUE THREAD

**Issue by pjdupreez** [jzoss/Git-Source-Control-Provider#11]
I have been using Git Source Control Provider for a couple of years now and nothing else comes close to it, but the update has caused a rather annoying issue. I have some solutions which contain multiple projects. I create each project on their own  (File->New Project, etc) so that each have their own folder and are not subfolders of my 'main' project. Each also have their own git repository.

Before updating to 1.4.1 I could individually commit, push, pull, etc each of the projects in my solution. Now, if I want to commit for example, regardless of the project I right-click -> source control...commit, it always defaults back to my 'main' solution. The only way around this is to open each project individually and commit them each in their own instance of visual studio. As you can see in the image below, only my 'Main' project has a status icon, whereas all my projects use to have :(

![git provider](https://cloud.githubusercontent.com/assets/1033864/11503356/cd2e0dfc-9848-11e5-9989-6f0c1f0422dd.png)

**Comment by jzoss** [comment]
Copy..An edge case I did not test :) .. I will have to setup a test repo, but it should be able to fix that. Thanks for the info, just 1 guy here updating all of this, and I have not been able to do as much testing as I would have liked.

**Comment by jzoss** [comment]
Just for clarification, you are talking about in the pending changes window, correct?

**Comment by pjdupreez** [comment]
Well, it's not just the Pending Changes but any item that I select from the menu that defaults to the startup project. commit, push, pull, history, all of it.

Selecting any sub project and going to Pending Changes shows me the pending changes of the startup project, even when hitting 'refresh'.

If it is possible, could you look into creating functionality so that when you select multiple projects and selecting 'commit' that it could open commit windows for all? If not, it's understandable.

Keep up the good work!!

**Comment by jzoss** [comment]
I am working on the issue.. I think I have an Idea what it is. Please if you can.. check out https://github.com/jzoss/Git-Source-Control-Provider/releases/tag/1.4.1.1 See if that is on the right track.. I think everything but auto updating the state in the solution explorer should be working. Getting late.. so I will hack at it more tomorrow if I can.

**Comment by teebee76** [comment]
I noticed a similar problem yesterday, I opened one of my solutions where I have lots of individual projects. I could no longer see the status i solution explorer, and the list in pending changes was empty (or not connected to the git-respository) If I started git bash from the pending changes window, it would take me to the solution directory instead of the project directory.

I installed 1.4.1.1 and it fixed all of those problems. @jzoss you are the man! a true life-saver :sunglasses: 

thanks for the good dev-work, and quick fixes :smiley:

**Comment by jzoss** [comment]
@teebee76 Thanks.

**Comment by ddobrev** [comment]
I think I have this bug too. Also, TortoiseGit Commit gives me "No working directory found.". I can see there has been a second beta but when will there be a stable release?

**Comment by jzoss** [comment]
Beta 2 is pretty stable. I may push it Monday.. I was just waiting for some other people to test it.. Why don't you give it a shot and tell me what you think. It will automatically update when the final 1.4.2 is released.

**Comment by ddobrev** [comment]
Beta 2 caused the status icons to reappear, thanks. However, TortoiseGit.Commit still gives the same error.

**Comment by ddobrev** [comment]
I am afraid, though, that the icons only appeared - they do not change when a file is edited. I think it may have to to with my set-up: https://github.com/jzoss/Git-Source-Control-Provider/issues/13#issuecomment-162260012 .

**Comment by ddobrev** [comment]
I tried switching to another branch and I got this from TortoiseGit:

Could not get a list of remotes.
libgit2 returned: Could not find repository from 'my home path/Projects/QtSharp/.git/modules'.

Git Source Control Provider obviously thinks this is my working copy. The actual repository I am working on is located at 'my home path/Projects/QtSharp/CppSharp/.git'. So it seems this provider has the same bug as MS's provider - it does not account for Git working copies checked out within another Git working copy of a different project. Let me know if I should file this problem as a separate bug.

**Comment by pjdupreez** [comment]
Just installed the 1.4.1.1 update and it fixed my issue. Thanks and well done!

**Comment by jzoss** [comment]
@ddobrev : It probably should be an separate issue, but I had a slow meeting this morning and it only took me 15 minutes to fix. Try 1.4.2 Beta 3.. And a note for all.. please hack at this.. If no issues are found it will become 1.4.2

**Comment by ddobrev** [comment]
I am afraid I can see no difference with Beta 3. TortoiseGit Commit, Revert and Switch still do not work, with the latter showing the same message, and the status icons are still not updated when a file is modified. Would you like me to file a separate bug for this?

**Comment by jzoss** [comment]
@ddobrev Sure.. And can you describe exactly you have your repos setup in the bug.. Also I added a GITTEST.7z file to the release.. It is how I setup my tests for this bug.. can you open that and make sure those work on your system, then tell me what I have setup incorrectly to test your situation.

**Comment by ddobrev** [comment]
I've just checked your test out. Other1 is checked out within Main and it does work here for me too. So my configuration apparently has some other specifics. As soon as I have figured them out I'll file you a bug.

**Comment by jzoss** [comment]
@pjdupreez Hey long time on this bug.. anyway can you check out this [comment](https://github.com/jzoss/Git-Source-Control-Provider/issues/30#issuecomment-218266355) about the new release .. It has some new multi-repo support. Just wondering what you think
