### ISSUE TITLE
when release a version for VS2019?

### ISSUE THREAD

**Issue by ArgoZhang** [jzoss/Git-Source-Control-Provider#112]
need a version for vs2019

**Comment by jzoss** [comment]
@ArgoZhang So that will be officially in the next release.. I want to make sure I test it a bunch first, however.. I have already released the beta build with VS2019 support. https://github.com/jzoss/Git-Source-Control-Provider/releases/tag/GSCP-CI

Test it and tell me how it works,.

**Comment by ArgoZhang** [comment]
@jzoss  great! i will install it later. :)
