### ISSUE TITLE
When editing a file and save (ctrl s)- it's not appear in the pending changes window until Refresh is clicked (than its appear)

### ISSUE THREAD

**Issue by shayH2** [jzoss/Git-Source-Control-Provider#116]
Hi,
When editing a file and save- it's not appear in the pending window (click on the refresh fix it), also the lock isn't remove from the solution explorer file.

my code is on remote disk (is it matter?)
I am using Tortoise git and vs17.

Is there any log that i can see what was fail?
Do i need to config any system parameters?

Thanks.

**Comment by jzoss** [comment]
Hi.. sorry for the delay.. I did a few quick test.. it might be the network path.. I'm not 100% sure. 

Logging in vs extensions is a bit difficult . I'm guessing the file watcher is not handling the path.. Can you do me a quick favor/test .. Can you map a network drive to where your code is.. and then open it from the mapped drive and see if that works?

**Comment by jzoss** [comment]
Hey. It appears to be fixed.. Please take a look and let me know if you still have issues.. Next release will be out soon or try the beta in the release tab.
