### ISSUE TITLE
*.bak files are automatically added to source control

### ISSUE THREAD

**Issue by ddobrev** [jzoss/Git-Source-Control-Provider#118]
Visual Studio regularly creates useless *.bak files. GSCP picks them up and adds them to source control. This makes it easy to accidentally commit them.

**Comment by ddobrev** [comment]
@jzoss grateful as I am for all of your work so far, this bug makes the plug-in unusable. VS constantly generates .bak files - there's no reason to do so at all but it does. The same goes for the .BASE aand .LOCAL files which appear while resolving conflicts. If the TGit commit window happens to already be open, these files cannot be seen as added without manual refreshing and are therefore committed to the repository. I can see your last commit is dated the 20th of February. In case you no longer have the opportunity to develop this project, I can only thank you for everything you've done so far but please say so so that I can start thinking about a solution.

**Comment by jzoss** [comment]
I'll take a look. I already have a exclusion list somewhere.. what happens
if you add those files to git ignore file?

**Comment by ddobrev** [comment]
@jzoss I'm extremely happy, to say the least, hearing you go on with the project on full power. :)
I'll definitely try fixing it by hand and it's most probably going to work but still fixing this would present a great convenience for future projects and users. And talking about the future - does your plug-in work with VS 2019?

**Comment by jzoss** [comment]
Yes, Since the last release 1.9.0 it works in VS 2019. As for my progress, I know I don't work on it as much as I used to, i'd be will to move the project to a org and have you as a second lead..

**Comment by jzoss** [comment]
@ddobrev because I like you.. here is a beta build.. Test to see if it fixed stuff for you.. I have not tested it yet. https://github.com/jzoss/Git-Source-Control-Provider/releases/download/GSCP-CI/GitSccProvider.vsix

**Comment by ddobrev** [comment]
@jzoss I highly appreciate it, thank you. I've installed this version and I'll let you know as soon as I've had to deal with such files again. However, I can tell you of an improvement right now – since Windows uses a case-insensitive file system, you should ignore casing when comparing the extensions. In particular, the temporary files used while resolving conflicts appear with upper-cased extensions.

**Comment by jzoss** [comment]
Fixed in next release
