### ISSUE TITLE
'Compare with last commit...' context menu entry always fails.

### ISSUE THREAD

**Issue by SwedishChef** [jzoss/Git-Source-Control-Provider#120]
It always compares to an empty file. 

Diff in Pending changes view is correct and also 'Compare..."' in  Pending changes view for the same file works as expected.

**Comment by wzx140** [comment]
I also encountered the same problem.

**Comment by jzoss** [comment]
@SwedishChef @wzx140 Are you talking about how it appear to be blank on 1 side of the compare?

**Comment by SwedishChef** [comment]
Yes, left side of the compare is always blank.

**Comment by jzoss** [comment]
Sorry for the long delay..  Will be fixed in the next version.. It would be nice if you could grab the test version here and see if it works on your setup 

https://github.com/jzoss/Git-Source-Control-Provider/releases/tag/GSCP-CI
