### ISSUE TITLE
Visual Studio 2015 Update 3 fails to load extension after update to version 1.9.1.

### ISSUE THREAD

**Issue by shintadono** [jzoss/Git-Source-Control-Provider#124]
"The 'BasicSccProvider' package did not load correctly. ..." error message shows up, and Source Control plug-in is set to 'None'.

(I uninstalled it and install version 1.9.0, which works fine, so far.)

**Comment by jzoss** [comment]
Well.. To be fair.. I didn't know it worked at all in 2015.. I'll take a look a see if I can fix it again.

**Comment by jzoss** [comment]
@shintadono Can do test something for me.. I don't have a 2015 instance running yet.. but can you install this latest test build.. https://github.com/jzoss/Git-Source-Control-Provider/releases/tag/GSCP-CI

**Comment by jzoss** [comment]
Ok.. made a VM.. It looks like its all fixed.

**Comment by jzoss** [comment]
@shintadono I just pushed a new release 1.9.2 out.. please let me know if it fixes your problem.

**Comment by shintadono** [comment]
Thank you very much. VS2015U3 could start it now without the error msg, and as far as I have quickly tested it, it seems to work fine.

 (And sorry I didn't react earlier - it was in the middle of the night, here in europe.)

**Comment by jzoss** [comment]
@shintadono No problem.. I figured that out when I looked at your profile. Glad it fixed everything!
