### ISSUE TITLE
Changes did not update solutionExplorer-glyphs and pending changes  on project

### ISSUE THREAD

**Issue by teebee76** [jzoss/Git-Source-Control-Provider#16]
When I did a commit on one of my projects earlier today, I noticed that the commit seemed to hang 
![image](https://cloud.githubusercontent.com/assets/5390116/11837530/cd98c2e2-a3e1-11e5-8184-0e93e9fa590a.png)
Even though it emptied the changed files list in the Pending Changes-window, it did not update the status of the glyphs/SourceControlStatusIcons on my project.
![image](https://cloud.githubusercontent.com/assets/5390116/11837604/440cd8fa-a3e2-11e5-902e-e38368a33ac2.png)
I guess this could be related to #11, since this is a solution with multiple projects where the projects have their own git repository.
I checked with the bash window and git status to confirm everything was pushed, so the pending changes window seemed to be up-to-date...
I did a restart of VS and the glyps were updated. However the strange thing is that if I save a change to one of the files now, the change is not shown in either pending changes or solution explorer. After about 6-10 seconds the glyph displaying uncommited changes will appear in solution explorer, but nothing displays in pending changes window. 

![image](https://cloud.githubusercontent.com/assets/5390116/11838278/4121d9de-a3e6-11e5-89e3-07ab1c921139.png)

I also noticed that in the new beta (which I installed today to see if that fixed this problem) the .gitignore and the symbol for it is seperated in the menu. (I drew a red circle around it in the screenshot to illustrate.

as you can see from the screenshot: git status shows a change,  Solution Explorer  does too (after a few seconds) pending changes does not :( 

And after changing files back and forth a few times, Solution Explorer stops refreshing the status as well. Not even pushing refresh in the pending changes window will fix it.
![image](https://cloud.githubusercontent.com/assets/5390116/11838426/4e89fd80-a3e7-11e5-8e7a-165036baeae5.png)

**Comment by jzoss** [comment]
@teebee76 OK.. I will look into it. The build I put out today should fix the Pending updates refresh in the beta.. I am moving away from the auto-update cycle.. I was doing it based on file updates.. and well in the last build I forgot to subscribe to the event. I noticed the autoupdate cycle could cause a slow down..Check out the new git ignore menu... Try the update gitignore :) IT's fun..

**Comment by jzoss** [comment]
Fixed in 1.5
