### ISSUE TITLE
.gitignore menu is seperated from its icon

### ISSUE THREAD

**Issue by teebee76** [jzoss/Git-Source-Control-Provider#18]
Like the title implies the menu icon for .gitignore and the text is seperated by multiple other options 
illustrated by this image
![image](https://cloud.githubusercontent.com/assets/5390116/11894580/6d61801a-a578-11e5-892f-6aa15d968418.png)

**Comment by jzoss** [comment]
Mostly Fixed.. does not have the pretty button next to it yet
