### ISSUE TITLE
Diff View tab/window is not visible/available

### ISSUE THREAD

**Issue by PureKrome** [jzoss/Git-Source-Control-Provider#2]
Just installed this plugin.

the DIFF VIEW tab/window is not available. It's gone. Kaput. Vanished.

And it's SOOO important :(

If I try and `compare` a *modified* file, (right click on the modified file -> compare) I get the following warning in the bottom message pane thingy: `The system cannot find the file specified`.

Help us Jon - you're our only hope!

Update:
- VS 2015 Prof
- Windows 10
- I'm hungry and sleepy :/

**Comment by jzoss** [comment]
Yea. I see this. I even had a bug TODO fix this in the source code.. and forget do to it.

**Comment by PureKrome** [comment]
![](http://i.giphy.com/4u8WdgQEMVaj6.gif)

**Comment by jzoss** [comment]
Fixed in 1.4

**Comment by PureKrome** [comment]
LGTM! Thanks!
