### ISSUE TITLE
Plugin sometimes fails to connect to git repo

### ISSUE THREAD

**Issue by wilhen01** [jzoss/Git-Source-Control-Provider#22]
Sometimes when I load Visual Studio the plugin fails to connect to the git repo. No branch name is displayed and if I press any of the buttons I get the following error:

![image](https://cloud.githubusercontent.com/assets/4677718/11954227/b3427944-a89e-11e5-96a1-3677e8103cc1.png)

Usually fixed by a restart.

**Comment by jzoss** [comment]
@wilhen01 -- So while I never was able to get this exact issue myself.. I am pretty sure I fixed it.. 1.5 Beta 1 is out if you want to give it a try. https://goo.gl/hqh9ow

**Comment by jzoss** [comment]
OK.. I'm pretty sure this is fixed.. I'll close it for now.. But I can reopen it if you encounter it again

**Comment by wilhen01** [comment]
Nice one, will install the new beta and let you know how I get on :+1:
