### ISSUE TITLE
'Compare...' context menu item not working if default git tool is used

### ISSUE THREAD

**Issue by 0x084E** [jzoss/Git-Source-Control-Provider#26]
I'm using CodeCompare as diff tool which is configured in `.gitconfig` with the following command
```
cmd = '"C:/Program Files/Devart/Code Compare/CodeCompare.exe"' /SC=Git /W "$LOCAL" "$REMOTE"
```
If I choose 'Default Git Tool' in the settings and click 'Compare..' in the context menu of 'Changed files' nothing happens and I see 'File not found' message in VS status bar.
I've tried different command path formats (foward slash, backslash, single/double quotation marks etc.) but I was not able to get it work.

**Comment by jzoss** [comment]
Ok.. I figured it out.. Not really a bug, but I may make something later to make this easier .. Anyway.. The issue is the "Program Files" space.. anyway I tried what they suggested on their site and that did not work either.. but when I changed what you had to 

[difftool "codecompare"]
cmd = \""C:/Program Files/Devart/Code Compare/CodeCompare.exe"\" /SC=Git /W "$LOCAL" "$REMOTE"
renames = true

It worked just fine.. try that and tell me what you think.

**Comment by 0x084E** [comment]
It's always a space :-)

Nice one, didn't thought about using this kind of double quoting, works fine also for the build-in git provider. I've also added this around $LOCAL and $REMOTE to avoid problems with spaces in these file names, too.
```
\""C:/Program Files/Devart/Code Compare/CodeCompare.exe"\" /SC=Git /W \""$LOCAL"\" \""$REMOTE"\"
```
Thanks for taking the time to investigate this!

**Comment by jzoss** [comment]
Yea.. I may try to fix it up somehow.. .my brain is starts to hurt from this 1.5 release.. anyway give beta 4 a try . tell me what you think .

**Comment by 0x084E** [comment]
Beta 4 is working fine for me. Multi repository support makes this extension a killer over the build in provider (and any other git extension I've used so far). The new tracking in 1.5 makes it even better and I haven't noticed any issues with it in beta 4 :+1:

**Comment by jzoss** [comment]
Sweet glad to hear it.. Nice that people like it .. Anyway.. There is a bug in beta 5... It's can use too many threads.. The next release *should* fix it.. Once you get the next release try switching branches a lot.. with lots of file changes..  Anyway. thanks for you help testing!
