### ISSUE TITLE
Filter pending changes by solution

### ISSUE THREAD

**Issue by jbestrom** [jzoss/Git-Source-Control-Provider#29]
I don't know enough about VS addin dev to offer a solution or I would.

But would it be possible to have an option to hide changed files that are not part of the solution that is opened?

I have a client and server solution that I open in 2 separate instances of VS they are in the same repo though and all the changed files show in each VS pending changes window.

Example:
Repo has changes to clientFile1, clientFile2, serverFile1

Client solution pending changes only shows clientFile1 and clientFile2

Server solution pending changes only shows serverFile1

Thanks

**Comment by jzoss** [comment]
It's a bit of work.. It might not be that bad.. because I do most of the filtering for the solution explorer refresh.. Anyway.. I am really close to 1.5 RC 1... I may have time to throw this in before I cut off more changes.. 

BTW..  this add-on is my first go at it... just sorta went crazy.. Probably bit off a bit more than I could chew.. But that's how you learn I guess :)

**Comment by jbestrom** [comment]
Yea i'm trying to learn a bit about it all now too so I may be able to help. I'm just not grasping yet how to cycle through all the projects/files in a solution. In my case I have the 2 main solutions with multiple projects each (all under one repo)

**Comment by jzoss** [comment]
Yea.. I think I have a good idea on how to do it.. I'll probably put it in to 1.5.

So.. If you are REALLY bored .. try checking out the code and compile it.  .. I just merged the branch into master.. IT SHOULD compile if you have visual studio extensibility tools 2015 installed :) 

So..I can describe how you would do it too.. I have all the plumbing to do it, so it should not be hard.. I'm mucking with the pending changes right now to so I may just put it in.. but if you are interested .. I will tell you what I did ..

**Comment by jbestrom** [comment]
Yep I have everything needed to compile. I'm actually right now doing a bit of debugging in/around the pending changes window because I'm seeing sometimes where it won't actually open the file i'm telling it to.

**Comment by jzoss** [comment]
Good.. Glad it built.. Took me a while to get the build to work right after I forked it..

**Comment by jbestrom** [comment]
When I double click on a file in the Pending Changes window I'm getting a "Value does not fall within the expected range" error.

![image](https://cloud.githubusercontent.com/assets/16417291/12587829/185278d6-c413-11e5-817e-955aa26a93cb.png)

The error is thrown from PendingChangesView.xaml.cs->GetSelectedFileFullName (384). 

However in OpenFile I think it is because the item.FileNames[0] is null?string.Compare(item.FileNames[0], fileName, true) == 0)

![image](https://cloud.githubusercontent.com/assets/16417291/12587964/bb5c1c1c-c413-11e5-8226-202f52121c09.png)

**Comment by jbestrom** [comment]
I'm diving head in now. I have a few minutes I'll see if I can work something out :)

**Comment by jbestrom** [comment]
Got it don't know how to fix it.

Seems to stem around if the solution is active.

How I reproduce it.
1.) Have changes in the repo
2.) Open VS solution file (I use from command line with sln file for less clicks)
3.) Once loaded double click on one of the files with changes in the pending changes window
4.) Get the error

Once you select in the Solution Explorer either the solution or a project the files then seem to open just fine.

One other thing I noticed is if I have a subfolder selected the error will still happen so seems like you have to have the solution or a project selected for the file to open.

**Comment by jzoss** [comment]
OK.. I will check it out.. Check out the latest C.I build.. put in the filter files into the pending changes.

**Comment by jbestrom** [comment]
I have been debugging and trying to figure it out. Seems to be around the "ActiveSolutionProjects" for some reason a top level folder that call doesn't like.

**Comment by jzoss** [comment]
check out the latest C.I. I think it's fixed.

**Comment by jbestrom** [comment]
Perfect the file opening is working great now I like that you basically just said always open instead of trying to find it.

The filtering you added earlier doesn't seem to be working correctly however.

I'll do some more testing on that and see if I can help with a solution.

**Comment by jzoss** [comment]
Oh I totally should have tested that a bit more :)

**Comment by jbestrom** [comment]
Some more info on the file opening issue for knowledge and may help in other places.

The call for ActiveSolutionProjects was causing the issue and I noticed that in the project there was the SolutionExtensions that has some solution/project stuff.

So locally I changed from ActiveSolutionProjects to SolutionExtensions.Projects() and it grabs all of the projects in the solution. I then was still having issues but it was due to https://msdn.microsoft.com/en-us/library/zk273747.aspx "Miscellaneous Files" being considered a project.

So locally I made the change in OpenFiles to be like below.

 var projects = SolutionExtensions.Projects();
            foreach (dynamic project in projects )
            {
	            if( project.Name != "Miscellaneous Files" )
	            {
		            foreach( dynamic item in project.ProjectItems )
		            {


It seems to have solved my issue with not being able to open files, but I think the solution of just opening the file is a better one as you don't need to do the logic to see if the file is open already VS will just set focus to that file if it is already open.


So point of that long post is I guess if you have to find all the files in the solution you can use those SolutionExtensions stuff and filter out the "Miscellaneous Files"

**Comment by jzoss** [comment]
@jbestrom I like it. I just went sorta cheap :)  But ... you way.. may be better.. I'm not sure 

Also check the latest build.. For the filtering .. https://github.com/jzoss/Git-Source-Control-Provider/commit/a1d51ee32699d8c06d69ef0d8d6c19acee92d07e

**Comment by jbestrom** [comment]
Still not working correctly. I have a pretty large solution and it seems like not all the files are getting put in SccProviderSolutionCache->_fileProjectLookup.

I set a break point and looked at everything in that _fileProjectLookup and it looks like mostly directories the few files I did find in there I modified and your filter worked as intended.

So it seems as though it just isn't grabbing all the files in the solution.

**Comment by jzoss** [comment]
I can't get it to break.. which does not mean anything.. just i haven't figured out the right way to break it.. I'm going to put out RC 2 ... let people hack at it a while.. but I am going to get this fixed before the release...

**Comment by jzoss** [comment]
@jbestrom 

Ok.. I didn't think it would take as long as i did.. but I think I did it.. Try the nightly build or pull down the latest code and tell me what you think.

**Comment by jbestrom** [comment]
Perfect initial tests seems like it is working! Great job. If I find anything else I'll do my best to pass along where I think it is happening.
