### ISSUE TITLE
Reoccuring Exception on History?

### ISSUE THREAD

**Issue by teebee76** [jzoss/Git-Source-Control-Provider#33]
I remember this exception was reported earlier, and not sure what the solution was, or if it was an external problem or not...

While trying out the other extension for gitflow in VS it invoked an install of Git to a preview version. 

At first I thought maybe it was related to this, so I uninstalled the preview-version of Git, and installed the latest stable 2.7.1 (64bit)

But still got the exception on GitUI when clicking History. On debugging the failing dragon.exe the FileNotFoundException was reported:

```
System.IO.FileNotFoundException was unhandled
Message: An unhandled exception of type 'System.IO.FileNotFoundException' occurred in Dragon.exe
Additional information: Could not load file or assembly 'Nito.AsyncEx, Version=3.0.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
```

don't know if it is of any help, if it has something to do with the configuration of gscp or if its just my install that messed it up. 

I uninstalled 64bit and installed 32bit version of git, restarted VS still the same error.

I will have a look at the closed bugs, to see if I can find the solution there.

**Comment by jzoss** [comment]
@teebee76 .. I think I fixed it in the latest C.I. build.. take a look let me know

**Comment by teebee76** [comment]
Yup, it works perfectly now :) case closed.
