### ISSUE TITLE
Glyph updating still not perfect :(

### ISSUE THREAD

**Issue by teebee76** [jzoss/Git-Source-Control-Provider#37]
I was doing a little coding in two different instances of VS, not sure if that was part of the problem or not, but then I noticed that even though I had done changes to a lot of files, they were all still being marked as unchanged i Solution Explorer.. 

Tried refreshing, opening and closing files, doing more changes and saving ... but SE was stubborn as a mule.. 

doing a vs restart fixed it as usual 

![image](https://cloud.githubusercontent.com/assets/5390116/13071489/13982cdc-d494-11e5-8d7a-a23ef6226129.png)

pending changes however seem to be perfectly up-to-date :+1:

**Comment by teebee76** [comment]
Something new and unexpected happened today too. Something I've never noticed before... 
(A picture tells a thousand words as they say, so here goes ...)
![image](https://cloud.githubusercontent.com/assets/5390116/13219812/ae1095a0-d972-11e5-9f80-665645c16ac5.png)

Never seen the blue checkmark before, what does it mean?

**Comment by jzoss** [comment]
@teebee76  Oh yea.. that is the check mark for staged.. Usually see it after a merge ..

**Comment by teebee76** [comment]
Thought it might be something like that :) 
btw:  found out that I didn't have the latest build. . I was still on 1.5.5  up to 1.5.7 now, and nothing fishy yet, I will let it run a while to see if it gets "out of sync" again
