### ISSUE TITLE
On latest develop (1.5.0.20) displayed changes have disappeared 

### ISSUE THREAD

**Issue by teebee76** [jzoss/Git-Source-Control-Provider#39]
When a file in pending changes is selected, the diff of that file is no longer displayed
![image](https://cloud.githubusercontent.com/assets/5390116/13316469/7e53b5d2-dbb0-11e5-8f4a-6840d47767ef.png)

**Comment by jzoss** [comment]
Opps!

**Comment by vaindil** [comment]
I'm having this problem on 1.6.0. I installed it for the first time ever today (never had an older version of the plugin). Git for Windows 2.8.2, Visual Studio 2015 Update 2 (14.0.25123.00), Windows 10 Professional x64. I tried pointing the plugin to both `sh.exe` and `git.exe`, neither has had any effect.

**Comment by jzoss** [comment]
@vaindil Can you make sure you expanded the window all the way.. sometime the stupid tab thing with the changes gets minimized. if not I will look into it.

**Comment by vaindil** [comment]
@jzoss Yeah, there's nothing there. This may actually be a new issue, it's not just the pending changes window. The toolbar shows 0 changes and no files show edits in Solution Explorer. I'm in the middle of a merge so hundreds of files are changed; the built-in git provider shows them (that's what I've been using). Editing a file and saving doesn't change anything in the display with the plugin selected--no edits appear, and the Solution Explorer icon next to the file doesn't update.

Screenshot with the pending changes window, it's positioned just above the bottom toolbar of Visual Studio in the image.

![capture](https://cloud.githubusercontent.com/assets/771134/15229555/88a6fd1e-185f-11e6-9e60-6af16b8eb979.PNG)

**Comment by jzoss** [comment]
@vaindil Yea It might be.. I am wondering... is it because of the merge.. If you by chance have a solution that has changes not in a merge can you see the changes.. Anyway.. if it is the merge .. at least that will be easier to track down..

**Comment by vaindil** [comment]
@jzoss My other solutions work correctly, it must be the merge. I'll open a new issue for this.
