### ISSUE TITLE
VS2015 Update 2 -> comment and switch branch tabs are inactive?

### ISSUE THREAD

**Issue by PureKrome** [jzoss/Git-Source-Control-Provider#41]
Hi.

just updated VS2015 to `Update 2`.

Opened up sln, changed a file .. and the `COMMIT`, `AMMEND LAST COMMIT`, `SWITCH BRANCH`, etc.. buttons/tabs are inactive.

the NAME of the branch did update (i switch branches to test this) .. and it does list the changed files, etc.

can't use this now.

![](http://i.giphy.com/FAX99ve3Egvok.gif)

**Comment by jzoss** [comment]
Well that's no good.  I'm at the build conference this  week..  So I may
not be able to fix it till next week..  But I may be able to ask someone
why they broke it

**Comment by PureKrome** [comment]
also, it's assuming it is broken (versus, just my machine is crapz0rd).

**Comment by jzoss** [comment]
If you right click in the solution explorer can you commit that way?

**Comment by PureKrome** [comment]
eventually, I can get the commit dialogue box to show up, that way.

**Comment by jzoss** [comment]
Ok last night over the very slow hotel wifi...  I installed rc2 and had no
problems..  Do you have the latest release very or the Beta 1.5.1 version
installed?

**Comment by PureKrome** [comment]
i just removed whatever version i had and re-installed the latest from the extensions vs store.

it says 1.5.0.0 

![image](https://cloud.githubusercontent.com/assets/899878/14235848/3d1807e2-fa4d-11e5-8d21-edcbaf6583c7.png)

**Comment by jzoss** [comment]
Can you try the latest C.I build https://github.com/jzoss/Git-Source-Control-Provider/releases/tag/GSCP-CI 
Tell me if it fixes you issue. .I'm looking into it right now.

**Comment by PureKrome** [comment]
That link is only _source code_. no exe binary.

**Comment by jzoss** [comment]
Sorry..  Deployment went out just as github.com went down today..  Didn't notice it got a bit messed up.  Should be there now.

**Comment by PureKrome** [comment]
still doesn't work.

**Comment by jzoss** [comment]
I have a theory.. Might have a idea where the bug is.. can you check your settings and see if you have the git.exe path set?

**Comment by PureKrome** [comment]
![image](https://cloud.githubusercontent.com/assets/899878/14336249/44035c64-fca5-11e5-81be-70be9d93203b.png)

**Comment by PureKrome** [comment]
![](http://upboat.me/aig/Aaaaaaaaaaaand/we're-back!/)

**Comment by PureKrome** [comment]
Latest code is working now.
