### ISSUE TITLE
Double-click in changed files list produces error

### ISSUE THREAD

**Issue by janellecom** [jzoss/Git-Source-Control-Provider#42]
When I double-click in the changed file list, I think it used to open that file in VS. Now I get the following error message: "/" is not a valid switch for this command.

VS2015 Update 2

**Comment by jzoss** [comment]
Can you try the latest C.I. build here.. https://github.com/jzoss/Git-Source-Control-Provider/releases/tag/GSCP-CI

See if your issue is fixed..? I will look into this issue a bit more.

**Comment by janellecom** [comment]
Uninstalled old one, restarted VS2015, installed new one, restarted VS, but
still see the issue with v1.5.0.58

**Comment by jzoss** [comment]
OK.. I will look in to it. .I can't recreate yet.. Anyway... 2 things you can do to help.. can you describe the path.. There might be a special case I can't see. Or you can check out the code.. and run the extension.. you would see the issue really there and can either fix it or tell me where it is.

**Comment by jbestrom** [comment]
Just for some added info I just tested master and dev and couldn't reproduce this either.

I'm also on VS2k15 Update 2

I use the double click to open file all the time.

**Comment by jzoss** [comment]
@jbestrom Thanks for testing that out. @janellecom and @jbestrom Could you test the latest new C.I.i build .. I just made a minor ( I hope) change to the way I open files.. Also if you still get an error it should give more details. Anyway.. the commit is in.. just waiting for the C.I build. same link as above.. no need to uninstall should just update. 

Went from 
'''
        private void OpenFile(string fileName)
        {
            if (string.IsNullOrWhiteSpace(fileName)) return;

            fileName = fileName.Replace("/", "\\");
            var dte = BasicSccProvider.GetServiceEx<EnvDTE.DTE>();
            dte.ExecuteCommand("File.OpenFile", filename);
        }
'''

to

'''
        private void OpenFile(string fileName)
        {
            if (string.IsNullOrWhiteSpace(fileName)) return;

            //fileName = fileName.Replace("/", "\\");
            var dte = BasicSccProvider.GetServiceEx<EnvDTE.DTE>();
            dte.ExecuteCommand("File.OpenFile", $"\"{fileName}\"");
        }
'''

**Comment by janellecom** [comment]
That last fix works!

Thanks for the great response! Love this add in
