### ISSUE TITLE
Changed files pane is not properly highlighting the selected item

### ISSUE THREAD

**Issue by PhilMurwin** [jzoss/Git-Source-Control-Provider#45]
The Changed files pane is not highlighting the selected item for the Light or Dark themes in Visual Studio 2015.  It appears to do so correctly in the Blue theme.  I've included screenshots of all three themes below, I have the same file selected in all three but you can only tell in the Blue Themed one.

![changedfiles_bluetheme](https://cloud.githubusercontent.com/assets/606839/14501870/20f5575e-016e-11e6-962d-0661386f7321.png)
![changedfiles_lighttheme](https://cloud.githubusercontent.com/assets/606839/14501932/6b41e714-016e-11e6-997b-2597a8c42730.png)
![changedfiles_darktheme](https://cloud.githubusercontent.com/assets/606839/14501951/81e62264-016e-11e6-964f-cb9f679f9482.png)

**Comment by jzoss** [comment]
@PhilMurwin  - Hey I have been trying to recreate this, but I have just not been able to.. Any tips on setup?

**Comment by PhilMurwin** [comment]
Environment:
* Windows 10
* VS 2015
* Various Azure and other MS installed extensions
* Git Source Control Provider (I reviewed my extension list and I don't have any other extensions that weren't pre-installed by MS/Visual studio)

My coworker is seeing the same issue; I can lay out a bit more detail:

1. Easiest to see with more 2+ files modified or new
2. Click a file in the list to view the changes in the right panel
3. When the changes appear in the right panel the file will not appear highlighted in the left panel
4. Clicking anywhere outside the file list (to make the file list lose focus) forces the selected file to become highlighted
    1. e.g. click in the right pane, click in the comments box above the file list, click into a window on a different monitor

If that doesn't help perhaps you can point me to the right point in the code to poke at.  I took a look around when I created the issue but wasn't sure where to look.

**Comment by jzoss** [comment]
Thanks for the more info.. I have yet to reproduce .. but I will try again later... 

I am super cool if you want to figure it out.. it has to be somewhere in PendingChangesView.xaml.cs 

Note : all you should have to do to get it running is make sure you install the vs extension development from the vs2015 setup and set the running program to GitSccProvider with these options

Run external program : C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe

Command line args: /rootsuffix Exp

**Comment by jzoss** [comment]
@PhilMurwin 
Can you install the latest C.I. build.. I was finally able to reproduce it.. and I think I have a fix. check it out https://github.com/jzoss/Git-Source-Control-Provider/releases/tag/GSCP-CI

**Comment by PhilMurwin** [comment]
@jzoss I just grabbed the C.I. build and this is working now in all three themes (blue, light, and dark). Thanks!

**Comment by jzoss** [comment]
Cool.. Thanks for testing!
