### ISSUE TITLE
50 % CPU for at least 15 seconds after a single file change in a large solution

### ISSUE THREAD

**Issue by ddobrev** [jzoss/Git-Source-Control-Provider#46]
https://github.com/mono/CppSharp is a fairly large solution with 51 projects. When I make a single change and save the file, my CPU usage jumps to 50 % for at least 15 seconds. It may not seem as much but during regular work changes are saved much faster and I have seen the difference stack. For comparison, using no source control, or MS's git provider (now called just "Git" on my machine, perhaps they renamed it in Update 2) raises the usage for 2 or 3 seconds.
@jzoss in case you want to test with my project, please have in mind that it does not have a hard-coded solution file, it has to be generated instead. In case you have trouble with this, just let me know and I'll provide any help you might need.

**Comment by jzoss** [comment]
OK.. I could be a lot of things.. I will look into it..well because I want to make it awesome.. @ddobrev can you tell me the right way to generate the solution? I guess if you want I could fork it and give you access to it to make the solution .. Or You could fork or branch.. Anyway.. I have an idea on where it might be.. Maybe..

**Comment by ddobrev** [comment]
@jzoss thank you for checking it out. So, the instructions are at https://github.com/mono/CppSharp/blob/master/docs/GettingStarted.md . As it's pointed out, you don't need to use premake on Windows, there are bats instead. Both are located in <root>/build. Just double-click them, first DownloadDeps.bat and then GenerateProjects.bat, and your solution will appear in build/vs<your_selected_version>.
Note: don't get confused by GenerateMake.bat, it's only used outside of Windows so it's irrelevant to this issue.

**Comment by jzoss** [comment]
@ddobrev So I'm working on the issue.. I think I know where it is.. and of course it's in a part of code i really hate. I added it to try and speed up the thing actually. Anyway.. I am sure they is a better way of doing what I am doing. .I just need to think about it.. maybe I'll ask peoples opinion .. However.. I mad a small change .. not fixed yet by any means, but please checkout the latest C.I. build from the release tab.. tell me if its better for you.. Ignore the broken status bar menus .. still working on those.

**Comment by ddobrev** [comment]
Thank you very much for your fast action. I am glad you know where the problem is, finding it is usually the hard part. It's a little late here and I'm going to bed but I'll definitely try the latest build tomorrow.

**Comment by ddobrev** [comment]
By the way, if you could explain the larger problem here and point me to the relevant code, I might be able to think of some reasonable suggestion tomorrow.

**Comment by ddobrev** [comment]
@jzoss I have just made about 7 attempts and I am afraid I cannot see any difference. Please implement that complete fix you have in mind and I'll be happy to test again.

**Comment by jzoss** [comment]
@ddobrev Ok.. tracking it down.. I will write up the whole issue when I get a chance. Please once again install the latest C.I. build. I found a issue using your repo that was causing much unneeded cpu cycles.. I still think the underlining problem is there, and it may or may not be an issue.. that is I have loop though all the changed files every time a file gets updated.. Ok without going too far in.. I keep a list of the the changed files.. When I get the next updated list of changed files .. I compare that to what I have, because if a file is now missing, that is it was in the old changeset and not the new one, I know it has been revert or committed. That check is what I think is causing the cpu to spike.. However, looking into this, I noticed that Untracked  files were being added to the changeset so in the case or you repo every update it had to search (and do a string compare ) to like 1500 files. So.. I files the untracked files, now I can look into making the changeset compare a bit faster.. But I can go into more detail on that later... Anyway.. check out the C.I. build see what you think..

**Comment by ddobrev** [comment]
I am afraid there's no change, not significant anyway. Let me tell you some more details about my set-up, they might help you.
I have three more repositories checked out under my root dir. They are not submodules or subtrees or in any other way related to the main repository. The first one is https://github.com/llvm-mirror/llvm.git in &lt;root&gt;/deps/llvm, then https://github.com/llvm-mirror/clang.git in &lt;root&gt;/deps/llvm/tools/clang and finally https://gitlab.com/ddobrev/QtSharp.git in &lt;root&gt;/examples/QtSharp. Note that you don't need to build, include in the solution or otherwise do anything with them. Just check them out somewhere under the root dir. I have given you my paths only for reference, it shouldn't matter where exactly you place the code.

**Comment by jbestrom** [comment]
@ddobrev Do you have VS2013 installed?

@jzoss If he does perhaps you could provide a 2013 version of the current code and @ddobrev  can test it there?

I say this because I still have an older version you created for VS2013 that I use often and it works great, but when I try to use on VS2015 I see all kinds of issues. I think the issues are more related to VS than this. So perhaps a test of VS2013 is in order? Not to say that there are still probably some improvements to be made I'm just trying to help :)

**Comment by ddobrev** [comment]
@ddobrev I am afraid I don't, and I won't because I don't need it at all and it's too large to leave it just lying around. However, I've never had issues with @yysun's old add-in for VS 2013 (https://gitscc.codeplex.com/releases/view/46589) so you might as well use that.

**Comment by jzoss** [comment]
@ddobrev I'll keep digging.. just added those repos as not submodules and still it's pretty speedy. Of course I am running a i7, with 16 gigs of memory and a SSD. ... I wonder if you could do me a favor .. 

can you start visual studio like C:\Users\z001h82>"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe" /rootsuffix Test 

Install the plugin and try again.. I wondering if a different plugin is fighting with it.

**Comment by ddobrev** [comment]
Should I install the dev version and then start it with this command or the other way around?

**Comment by jzoss** [comment]
Oh. Yea. Didn't think about that. :) Open the new visual studio .. Add this feed to Visual Studio's extension manager from Tools -> Options -> Environment -> Extensions and Updates: http://vsixgallery.com/feed/extension/GitSccProvider.Microsoft.88d658b3-e361-4e7f-8f4d-9e78f6e4515a

That will let you install the latest C.I. build

**Comment by ddobrev** [comment]
I had actually got it from https://ci.appveyor.com/project/jzoss/git-source-control-provider-bfftg/build/artifacts, is it not the same?

**Comment by jzoss** [comment]
Yea.. it is the same

**Comment by ddobrev** [comment]
@jzoss I did as you said. I ran "C:\Users\z001h82>"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe" /rootsuffix Test" and then installed Git SCC from http://vsixgallery.com/feed/extension/GitSccProvider.Microsoft.88d658b3-e361-4e7f-8f4d-9e78f6e4515a. This time the CPU got up to no more than 20 % for no more than 3 seconds. So the reason is in the interaction with some of my other add-ins. I am now going to start disabling them one by one until I find the offender. I am then going to report the results.
In the mean time, do you have further improvements to performance in mind? If so, please add them, they are always useful.

**Comment by jzoss** [comment]
@ddobrev Actually I do have a few.. I don't think the cpu should spike that much.. Even 20%.. but.. What could be going on is it just take the cpu because it available. However.. still I think I can rethink a few things and make it better. I am firing a few events too often.. Give me 15 minutes I may have another test build for you.

**Comment by ddobrev** [comment]
@jzoss it's Refactoring Essentials, on its own. Now that you have sped Git SCC up - which I did notice after all with a greater amount of testing - it's as slow with it as without it (or without any SCC provider, for that matter). So when you have implemented all ideas about performance you have in mind, please consider this issue closed. I'll take it with them. Of course, let me know if you want me to test any more builds.
Note: please be careful with those events because even I know that the lack of enough notification may easily result in irregularly updated glyphs in Solution Explorer.
Thank you very much for your work. I am looking forward to the official release containing all these improvements to performance.

**Comment by jzoss** [comment]
@ddobrev ok.. took me a bit longer.. Just pushed a few more changes.. went through my update cycle and eliminated most/all of my string ToLower and == .. I noticed it seeming zippier and cpu on my pc went down.. I did break one minor thing.. If you revert first thing before you make other changes the solution explorer does not update till you make a change.. but I can fix that .. just wanted to see if I was getting better. before you went off to bed.

**Comment by ddobrev** [comment]
Excellent, I'll try this build if you upload it. About that issue, no worries, I'll switch back to the stable version after the test and I'll update once you release the fixes.

**Comment by jzoss** [comment]
So on a side note.. Performance wise.. The profiler I used results went from 
![screenshot_2](https://cloud.githubusercontent.com/assets/3586254/14650740/935c7a16-0632-11e6-89da-42da49115806.png)


to 

![screenshot_1](https://cloud.githubusercontent.com/assets/3586254/14650749/985c9a0a-0632-11e6-8874-92696d8e378c.png)


So that looks much better to me!

**Comment by ddobrev** [comment]
Wow, impressive indeed! I am really happy this issue has been literally erased. :)

**Comment by jzoss** [comment]
@ddobrev Looks like I forgot to add a file. Once the C.I. builds is done.. It automatically deploys the build to the release tab and  vsixgallery.com  Should be there in a few minutes

**Comment by ddobrev** [comment]
Release tab? Do you mean you're deploying a stable version now? If so, it's going to have that small regression you described fixed, correct?

**Comment by jzoss** [comment]
No.. the release tab gets a per-release ci build . Just the one you get from appveyor. It's auto updated on every C.I. build.

**Comment by ddobrev** [comment]
I installed the pre-release, definitely works faster and I haven't seen any trouble. I think I'll keep it until the stable version is released.
Thank you for your work.

**Comment by ddobrev** [comment]
I've just noticed a problem: when I include in a project a file which I haven't yet added to source control, it's displayed as if it already is (a blue lock).

**Comment by ddobrev** [comment]
I reverted to the stable version and the files are once again correctly displayed with a plus.

**Comment by jzoss** [comment]
Yeah I am not surprised..  I will have to fix that one.  I guess I made it
a little too efficient  :)

**Comment by ddobrev** [comment]
@jzoss if there are no more optimisations to do or regressions, please close this one.

**Comment by jzoss** [comment]
Yea.. Planning on it. Just finishing testing it :) I will probably have 1 more c.i. build for you to test.

**Comment by ddobrev** [comment]
Will do.

**Comment by jzoss** [comment]
All right..  Check out the latest build..  I think if should be to you liking!

**Comment by ddobrev** [comment]
It's a little slower, I guess it's the necessary trade-off for fixing the regression. In any case, much better than it was when I filed this.

**Comment by jzoss** [comment]
@ddobrev Ok last build for this.. I promise.. I made a small change in the latest C.I. build.. check it out... I don't think it is very big.. but the big issues are gone, so it's a bit harder to track down them now :)

**Comment by ddobrev** [comment]
It's fine. I can see the CPU usage rise, then drop for a second and then rise again for much longer. My tests have confirmed that the second rise is caused by other add-ins so you're good to go. :)

**Comment by ddobrev** [comment]
It's also better than the previous build.

**Comment by jzoss** [comment]
@ddobrev OK.. I still blame you for me hacking at performance :) Anyway.. I fixed a big bug.. Well a small bug but it makes a big performance difference.. Anyway check the latest C.I. build and tell me what you think.

EDIT: My build is going super slow.. the C.I. build should be there.. soon.. tell me if you need me to upload it manually.. Anyway.. initial tests.. the cpu spike is gone.. :)

**Comment by ddobrev** [comment]
I'll gladly try it but I can see you keep queuing new builds. When the build is complete, I'll download and test.

**Comment by jzoss** [comment]
@ddobrev Just that the latest one now.. not sure why I can't deploy to github right now.

**Comment by ddobrev** [comment]
It's MUCH faster, thank you! I've had a minor bug with the new release, though - sometimes changed files are marked with the blue tick instead of the red one, usually when files have already been changed before loading the solution. Could you please check this one? After that you might as well update the official release.

**Comment by jzoss** [comment]
@ddobrev Yea.. that's sorta a feature.. :) The blue check is when the file has been staged.. but not commit-ed. I guess I could change it

**Comment by ddobrev** [comment]
Oh, I see. It's OK then.

**Comment by jzoss** [comment]
So.. this is lame. look at the bug https://github.com/jzoss/Git-Source-Control-Provider/commit/1d090f2687cf79d6905db0335fcb9fcb44274359

misplaced  }

**Comment by jzoss** [comment]
@ddobrev. I may fix one more little issue..  But you are right..  Probably time to release

**Comment by jzoss** [comment]
@ddobrev ..Just pushing out 1.6.3.. with the performance update.

**Comment by ddobrev** [comment]
Thanks. The copy in the VS gallery hasn't been updated for some reason. I can download the release manually but I guess you want the gallery to have the latest version too.

**Comment by ddobrev** [comment]
To be exact, it seems it doesn't actually consider 1.6.3 different than the .110 nightly I have here.

**Comment by jzoss** [comment]
@ddobrev it should update.  It can take a bit for visual studio to detect it.  The nightly should be 1.6.2.110.. So it will update eventually

**Comment by jzoss** [comment]
@ddobrev .. Did it ever update?

**Comment by ddobrev** [comment]
I don't know. I decided to remove the add-in and install it again from the gallery. But when I went there, it showed 1.6.3. This was before I posted my previous comment. It seems to me that 1.6.3 was actually uploaded to the gallery but the difference in versions could not be detected by VS.
