### ISSUE TITLE
Double-click on Diff window doesn't open code window

### ISSUE THREAD

**Issue by NightOwl888** [jzoss/Git-Source-Control-Provider#47]
In the Visual Studio 2012 (original) version, you could double-click on the Diff window on any line and it would open the code window and put the cursor on that same line (and ensure it is within the viewport). It is a feature that I got really used to using. But in this new version, it no longer works.

I am reporting this as a bug, since it is more or less a (useful) feature that no longer works.

**Comment by jzoss** [comment]
@NightOwl888 I added this feature to the latest C.I. build. I am getting closer to a release, it is stable but the status bar controls don't work yet. Feel free to install and test it .. When the release come out, it will auto update ..

**Comment by jzoss** [comment]
@NightOwl888 Check out the latest C.I. build in the release tab.. It will probably become the next release ... tell me if this is working the way you like.

**Comment by NightOwl888** [comment]
I downloaded 1.6.2 and this appears to be working again. Thanks.

**Comment by NightOwl888** [comment]
Well, it is *almost* working the way it was before. I noticed that when double-clicking in the previous version the insertion point went to the end of the word that you clicked on. Now it puts the insertion point at the beginning of the line.

This is something I can live with, but it is a bit different than the behavior before.
