### ISSUE TITLE
Cannot use git source control provider any more

### ISSUE THREAD

**Issue by AndyZhang001** [jzoss/Git-Source-Control-Provider#49]
Can still see it in the source control plug-in dropdown list. But nothing happen when select it.

version: 1.6
vs version: vs2015 update1

Previously saw some error in ActivityLog:
513  Begin package load [BasicSccProvider] {C4128D99-2000-41D1-A6C3-704E6C1A3DE2}  VisualStudio 2016/05/12 08:17:14.574
 
514 ERROR SetSite failed for package [BasicSccProvider][Could not load type 'Microsoft.VisualStudio.Shell.ProvideSourceControlProviderAttribute' from assembly 'Microsoft.VisualStudio.Shell.14.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.]:{ at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type) at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext) at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments) at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg) at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent) at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit) at System.RuntimeType.GetCustomAttributes(Type attributeType, Boolean inherit) at Microsoft.VisualStudio.Shell.Package.RegisterToolboxItemDiscoveryFactories() at Microsoft.VisualStudio.Shell.Package.Initialize() at GitScc.BasicSccProvider.Initialize() at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp)} {C4128D99-2000-41D1-A6C3-704E6C1A3DE2} 80131522 VisualStudio 2016/05/12 08:17:14.575 

515 ERROR End package load [BasicSccProvider] {C4128D99-2000-41D1-A6C3-704E6C1A3DE2} 80131522 VisualStudio 2016/05/12 08:17:14.576 
516 Warning Package failed to load; error message suppressed by skip flag {C4128D99-2000-41D1-A6C3-704E6C1A3DE2}  VisualStudio 2016/05/12 08:17:14.576

**Comment by jzoss** [comment]
Crap..  See the issue..  It is because you don't have Release 2 installed.  You  can either update or uninstall 1.6 and grab 1.5.1 from the release tab in GitHub.. Just turn off auto update for now.

**Comment by jzoss** [comment]
@AndyZhang001 Hi.. If you have not upgraded to Update 2 yet.. can you head over here https://github.com/jzoss/Git-Source-Control-Provider/releases/tag/GSCP-CI and download that build and test it for me... That would be awesome! I think I have it sorted out..

**Comment by AndyZhang001** [comment]
@jzoss Tested the link, it works now on 2015 update 1. Thanks a lot.

**Comment by jzoss** [comment]
Cool..  Released a new build on the official release track..  Thanks for helping me fix the issue!
