### ISSUE TITLE
Git History Crashes in v1.4

### ISSUE THREAD

**Issue by mnadel** [jzoss/Git-Source-Control-Provider#5]
Just updated to 1.4. Right-click a file in Solution Explorer and select Git -> History.

Get a popup: "GitUI has stopped working."

I'm using Git 2.6.3, but this previously worked (though opened up a UI I've never seen instead of the VS History view).

**Comment by mnadel** [comment]
Same result when I use Git 1.9.7.

**Comment by jzoss** [comment]
Fixed in 1.4.1
