### ISSUE TITLE
Disabled by VS2015

### ISSUE THREAD

**Issue by benny856694** [jzoss/Git-Source-Control-Provider#56]
sometimes, this extension will be disabled by VS2015, don't know why.

**Comment by RaveNoX** [comment]
@benny856694 do you have some information about this problem?
I also have this but don't know how to fix.

**Comment by RaveNoX** [comment]
For users which also has this problem:
1) There may dublicate extension: http://david.gardiner.net.au/2015/11/web-essentials-2015-extension-keeps.html
2) You may also try clear MEF cache with this extension: https://github.com/madskristensen/ClearComponentCache

**Comment by benny856694** [comment]
removing and reinstalling the extension solved the problem
