### ISSUE TITLE
BasicSccProvider won't load

### ISSUE THREAD

**Issue by SteveOwensFDC** [jzoss/Git-Source-Control-Provider#57]
VS 2015, latest updates applied.  On trying to switch to the Git provider, VS shows a dialog (attached) with "The 'BasicSccProvider' package did not load correctly."  Also attached is ActivityLog.xml, for what it's worth.

I have tried uninstalling/reinstalling, installing a recent nightly (v1.6.4.9), and finally reinstalling Visual Studio itself, but I can't seem to clear the error.

[ActivityLog.zip](https://github.com/jzoss/Git-Source-Control-Provider/files/415979/ActivityLog.zip)

![git sc provider load error](https://cloud.githubusercontent.com/assets/17296534/17633183/fddcf5d4-6099-11e6-9661-a764f68b69e2.png)

**Comment by jzoss** [comment]
Thanks.. I will take a look. I wonder if it may be colliding with another extension. Anyway if you WANTED to you could check out the code an run it and see what happened. I will see if I can figure it out on my end.

**Comment by SteveOwensFDC** [comment]
I’m willing to give it a try, since the built-in MS Git is not working for us.

To start, I’m not sure how to get set up for Extension development.  Installed the SDK, but I’m still getting an error for Microsoft.VisualStudio.ErrorHandler.  I see two different versions in the GAC, 10.0 and 14.0.

Am I barking up the wrong tree here?  Is there some other step I need to take to be able to build?

Once I get it built, how exactly do I ‘run’ it?

**Comment by jzoss** [comment]
Hey thanks for your help.. I'll get you on the right track.. First.. just as another test... for to bug here... https://github.com/jzoss/Git-Source-Control-Provider/issues/54 here is a special zip install there.. follow the directions and try and install it.. See if that fixes the bug.. If so, I think I can fix your issue. 

Anyway, to build you go to the setup for vs2k15 and install all the extension dev stuff. You can make sure it works by starting a new extension project and just running it. After that if you check on the git extension ... set startup project to GitSccProvider .. go to properties on that project.. debug tell it to start external program .. put in ""C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe"  and in the command line args put in "/rootsuffix Exp" and you should be good to go.

**Comment by SteveOwensFDC** [comment]
Sadly, the .zip version did not fix my error.

I still can’t get the .sln to realize that I have Microsoft.VisualStudio.dll in multiple places, most notably the GAC.  I have tried adding both the 2.0 and 4.0_14 versions as a reference in the project, but it keeps giving me errors that look like a missing reference to VisualStudio or VisualStudio.Shell .  I’m stumped.

I tried running a barebones extension project (using the debug settings below), and it *seems* to work, but what do I know?

**Comment by jzoss** [comment]
Odd.. I will take a look.. All those references should be added by nuget I think.  I tried it a few computers and I worked for me.. but I may be able to track it down. I hate to ask, do you have another pc to test on for reference ?

**Comment by SteveOwensFDC** [comment]
I will try it on my home machine later tonight.

**Comment by jzoss** [comment]
2 things.. I updated the nuget references and pushed , so try getting the latest dev branch and test that. Don't think that will fix it but hey, worth a shot. 

Also the target framework should be 4.5.2. Don't know what that would change but can you make sure that is the same on your computer?

**Comment by SteveOwensFDC** [comment]
Wow, the updated solution looks a lot different.  Everything compiles now, my plugin now mysteriously is working.

I get the warning “if you switch plugins the solution will close”.  Is there a way in the .sln file I can force the plugin to be the Git Provider?

**Comment by jzoss** [comment]
Cool.. glad to hear it.. No idea why :+1: 

For the second part.. that is a "feature" VS2k15 .. Once you switch and reopen it should stay that way .

**Comment by SteveOwensFDC** [comment]
Hmmm. The change doesn’t “take” for me with my existing projects cloned from the remote repo.  I will have to fiddle some more to see what I can make happen.

**Comment by SteveOwensFDC** [comment]
I have a possible reason for my initial troubles and why it started working.

After having issues with an extension, I often disable everything I can and try it again.  Once the Git SCP was working, I enabled everything.  When I restarted, I had a load error with Git Tools.

Since Git SCP has a right-click menu of everything, I disabled Git Tools.  I mention it in case it’s something to put as a caveat in your install doc.

**Comment by jzoss** [comment]
Yea I can see that.. Both plugins were forked from the same project, just went different directions ..  Anyway tell me what you think of the plugin.. I hope it works for you. If you want to feel good and support me a bit, no need for $$ just give me a nice review on the extension site and/or tell a few other people how awesome it is.

**Comment by SteveOwensFDC** [comment]
I’m in the process of rolling this out to the team, and one machine (so far) had an issue.

When switching providers, Git SCP is in the list, but when I click on it, it immediately switches back to the previous setting.

I’ve tried installing the latest CI version but no luck.  Unlike me, this person has very few 3rd party extensions installed, so it’s not likely to be the type of conflict I had with Git Tools.

Any ideas?  Is there something I can supply for debugging?

**Comment by jzoss** [comment]
Sorry I am on vacation today , so I am not at my dev computer. Besides checking out the code on his computer and trying to debug, I'm not sure off the top of my head. I seems to remember this happening to some else before, I'll look through the closed bugs when I can..

**Comment by jzoss** [comment]
What update of visual studio does he have?

**Comment by jzoss** [comment]
@SteveOwensFDC Hey, did you get it working? I am finishing up the next release and I want to make sure it's working with you before I do.
