### ISSUE TITLE
[Request] Visual character count for commit subject line.

### ISSUE THREAD

**Issue by PureKrome** [jzoss/Git-Source-Control-Provider#59]
It's an art trying to make succinct commit subject lines that don't get auto-cut-wrapped in GitHub, etc.

So maybe we could have a simple char-counter so we can see how many we have typed? 

eg...

![image](https://cloud.githubusercontent.com/assets/899878/18538565/987182ea-7b52-11e6-93e3-68ab83bcffd7.png)

EDIT: it only reads the char count for the **first** line (because that's the subject line).

**Comment by jzoss** [comment]
@PureKrome -- Still looking for this feature?.. I know it's been a while.

**Comment by PureKrome** [comment]
yes please. I still use this plugin :blush:

**Comment by jzoss** [comment]
Done in latest C.I. Build.. Will be released in 1.8
