### ISSUE TITLE
Null error => Popup dialog box with 'Object reference not set to an instance of an object`.

### ISSUE THREAD

**Issue by PureKrome** [jzoss/Git-Source-Control-Provider#6]
with version 1.4..

When I click SETTINGS, i get this pop up dialogue...

![image](https://cloud.githubusercontent.com/assets/899878/11385024/faefeb28-9368-11e5-8124-42f7f785ccc0.png)

Not sure why, etc :( :(

(also note the wrong colour background, which is the same as #1 )

**Comment by jzoss** [comment]
Fixed in 1.4.1

**Comment by PureKrome** [comment]
Ta mate!

**Comment by PureKrome** [comment]
version 1.4.1 getting pushed up to https://visualstudiogallery.msdn.microsoft.com/51e11ccc-6334-4873-912d-bf5025eb115d any time soon?

**Comment by jzoss** [comment]
Yes.. I was trying to fix the revert issue first :)  I will push it out tomorrow or Monday.. After I awake from the turkey comma

**Comment by PureKrome** [comment]
# !! T U R D U K E N !! #

![](http://s.wsj.net/public/resources/images/OB-OD861_turduc_G_20110603012018.jpg)
