### ISSUE TITLE
Rename the Plugin

### ISSUE THREAD

**Issue by PureKrome** [jzoss/Git-Source-Control-Provider#63]
![image](https://cloud.githubusercontent.com/assets/899878/19541230/760182fe-96b0-11e6-8579-2c258421d4a5.png)

![image](https://cloud.githubusercontent.com/assets/899878/19541243/89bc7506-96b0-11e6-9b7b-1435da22c57b.png)

I had to install the plugin today on a temp machine. First thing i noticed was the _name_ of the plugin.

It 'feels' like this is a plugin made for the YEAR 2015 and as such .. it feels _old_ now 'cause we're at the end of 2016 (at the time of this writing).

Can we rename the plugin?
Will this have any impact on the existing plugin and the number of downloads, etc?

**Comment by jzoss** [comment]
I agree.. I think I asked a while back about renaming it, if anyone had suggestions.. I am totally open to a rename. Suggest something cool!

**Comment by PureKrome** [comment]
- Easy Git
- Simple Git
- Git GUI
- Git for Visual Studio
- Git it
- Go Git it.

**Comment by jbestrom** [comment]
Looks like Easy Git is already taken from your screen shot.
Git GUI is already an app for git for windows.

I like

* Simple Git
* Git for Visual Studio

or my suggestions

* Better Git
 * VS Git

**Comment by cyberium** [comment]
- Git for Visual Studio
- Easy Git Integration Plugin For Visual Studio -> EGIP
- Easy Git Integration Tools For Visual Studio -> EGIT

**Comment by jzoss** [comment]
OK..  Survey link..  https://www.surveymonkey.com/r/7H8VNLG

**Comment by jbestrom** [comment]
So what did you decide?

**Comment by jzoss** [comment]
After 13 responses .. Better Git and Easy Git Integration Plugin For Visual Studio -> EGIP are tied... I may flip a coin.

**Comment by jzoss** [comment]
Ok.. just popped in my head.. what do people think 

Easy Git Integration Tools For Visual Studio ->  EZ-GIT

**Comment by jbestrom** [comment]
I like it!

**Comment by PureKrome** [comment]
Refactor suggestion: `Easy Git Integration Tools -> EZ-GIT` ... drop the for VS because this is implied. we _are_ in the VS gallery.....

**Comment by jzoss** [comment]
@PureKrome -- Love it! Ok Going to do a release soon to change the name and hopefully add VS 2017 support.

**Comment by jzoss** [comment]
@PureKrome @jbestrom @cyberium 
HI all question..

So it came up here that https://github.com/jzoss/Git-Source-Control-Provider/issues/67 that @ddobrev really hates the new name.. Also I have noticed that there is another project called something really close to Ez-git.. Anyway not to cause issues .. but he suggest we rename it to Git Source Control Provider 2017. I don't have a opinion really. What do people think?

**Comment by PureKrome** [comment]
>Git Source Control Provider 2017

Hate it.

1. it sounds like the bad old days of MS -> Visual Studio 2012 Winter Package Service Release 1 for Enterprise EU-A .. etc ... 
2. What happens in 2018, 2019, etc?

**Comment by ddobrev** [comment]
@PureKrome I'll update it myself in 2018 or 2019 or whenever. I prefer just "Git Source Control Provider" myself but @yysun's add-in has taken that name and he cannot be asked to remove it from the VS gallery because it still works with VS 2010 and 2013. The perfect solution would be for this GitScc to work with those too at which the package wouldn't need a year but I guess it's too much mostly pointless work. So I'd much rather have "Git Source Control Provider 2017", both as a homage to @yysun's work, which I have used for years myself, and as a simply more descriptive name.

**Comment by jbestrom** [comment]
How much of a problem is it to just  leave the year off? I mean this version only works in 2015+ and the original only works in 2013 and below.

Could it just be Git Source Control Provider. I mean most people who would use this extension shouldn't have any trouble figuring out which one to use. I don't even think VS will allow you to install the wrong version.

**Comment by ddobrev** [comment]
I am OK with "Git Source Control Provider" without a year as long as any possible confusion would be negligible. I guess @jzoss would have to say about it because this concerns how easily users would find and use his work.

**Comment by jzoss** [comment]
I'll close it for now again.. I'll leave it as it for now.. I want to get it out  and I've been a bit busy lately.
