### ISSUE TITLE
EZ-GIT is always disabled?

### ISSUE THREAD

**Issue by PureKrome** [jzoss/Git-Source-Control-Provider#65]
I'm trying to see if this is just a problem with _my_ setup ... but ...

every time I start VS2015 EZ-GIT is **disabled**. I also have to go and:

- Enable EZ-GIT (Tools -> Extensions & Updates)
- (Sometimes) Select EZ-GIT as the prefered Source Control provider (Tools -> Options -> Source Control)

anyone else having this issue?

**Comment by davedowns** [comment]
I also have that issue, using Visual Studio 2015 Community Edition.

**Comment by jzoss** [comment]
Check out https://github.com/jzoss/Git-Source-Control-Provider/issues/56 Seems like it happens sometimes

**Comment by davedowns** [comment]
I had to uninstall twice but that's fixed it for me.

I uninstalled the extension, restarted, checked the extensions list and it was still installed. I uninstalled again, restarted again, check the extensions list again and this time it was gone. I could then reinstall and everything work as it did before the recent update.

That seems to mirror the problem David Gardiner was having with Web Essentials (linked to in #56 - [http://david.gardiner.net.au/2015/11/web-essentials-2015-extension-keeps.html](http://david.gardiner.net.au/2015/11/web-essentials-2015-extension-keeps.html)) and is presumably related to the recent name change and possible automatic extension updates?

**Comment by PureKrome** [comment]
Just started up another instance of VS2015 a few mins ago.

Plugin was disabled again. Also it has the name Easy Git Integration Tools (EZ-GIT) still (not sure if the name revert was suppose to happen before any next updates, etc)...

**Comment by jzoss** [comment]
I didn't rename it.. I was supposed to get it out before 3/1/2017 and I didn't want people to have it auto-disable again.. I was going to look into fixing that.. I think it might have something to do with it updating in 1 instance on Visual Studio while you have another open. Anyway... LAMO

**Comment by jzoss** [comment]
@PureKrome Are you running VS as admin or not? Just wondering.

**Comment by PureKrome** [comment]
nope. not as admin. always as normal user.

(my user account is an admin user though). I'm assuming those are two different things, though.

**Comment by jzoss** [comment]
Yes.. I just want to see if I can figure out the issue. I noticed I have
several plugins disabled in the same way.

**Comment by davedowns** [comment]
I just had it happen again as well. As before, uninstall, restart VS, uninstall, restart VS, reinstall seems to have fixed the issue.

**Comment by jzoss** [comment]
Going to close it.. It seems to happen sometimes for all extensions.
