### ISSUE TITLE
VS2017 Support

### ISSUE THREAD

**Issue by jbestrom** [jzoss/Git-Source-Control-Provider#66]
If I recall correctly you were working on 2017 support, how is that going?

**Comment by jzoss** [comment]
I have a version that works.. just testing it a bit.. I'll check it in soon enough for people to test.

**Comment by jzoss** [comment]
Ok.. here is the first test release for 2017 and 2015.. Please test it in both. 

https://github.com/jzoss/Git-Source-Control-Provider/releases/tag/Pre-1.7

**Comment by jbestrom** [comment]
2 days and so far seems good. I'm closing this and will open another issue if I see anything else.

**Comment by jzoss** [comment]
Cool.. Also check out the same build in Vs 2015... I've been using that and it seems good to me.

**Comment by jzoss** [comment]
Again.. check out that link for the latest build..Test it out for me a little. If it still works fine, I'm going to merge it into the main dev branch.
