### ISSUE TITLE
Reverting / Undo file changes, just hangs .. and the UI isn't refreshed.

### ISSUE THREAD

**Issue by PureKrome** [jzoss/Git-Source-Control-Provider#7]
Tried to revert/undo a file .. and the VS UI just hung for about 15 odd seconds .. and then nothing.

repeated this a few times .. same thing.

When i jumped over to TortoiseGIT it looks like it was reverted, though. So _i think_ the UI isn't refreshing correctly?

**Comment by jzoss** [comment]
Fixed in 1.4.2

**Comment by PureKrome** [comment]
thank you kindly sir!!!

**Comment by jzoss** [comment]
Fixed in the beta release.. working on finishing the release. https://github.com/jzoss/Git-Source-Control-Provider/releases/tag/1.4.1.1
