### ISSUE TITLE
Show Log and Blame don't work for TortoiseGit integration

### ISSUE THREAD

**Issue by OvidiuCaba** [jzoss/Git-Source-Control-Provider#74]
**Steps to reproduce**

1. Select any file
2. Right click, open context menu, select menu option Git\Show Log
3. Observe that **the Log Messages table does not contain the history of the selected file**. Instead it contains only a single row: "Working tree changes"
4. Close the Show log window, then select any file
5. Right click, open context menu, select menu option Git\Blame
6. **An error is displayed**

I use VS 2015 and VS 2017.

**Comment by jzoss** [comment]
Awesome.. I love when people add bugs then fix them!

**Comment by OvidiuCaba** [comment]
Thank you for the nice words! I am happy to help if I can :)

**Comment by jzoss** [comment]
@OvidiuCaba Can you try the latest dev build here.. https://github.com/jzoss/Git-Source-Control-Provider/releases/tag/GSCP-CI

See if the issue is fixed for you. Thanks

**Comment by OvidiuCaba** [comment]
@jzoss , I installed the version 1.7.1.14 and the issue is not fixed.

**Comment by jzoss** [comment]
https://github.com/jzoss/Git-Source-Control-Provider/commit/282eca6942d11fa044ee90f00e28683bd59e5b4a#diff-8afcfdcb33f8ff84996edcfa247c1dee

Look like it.. I will have to take a look. What version of tsvn do you have?

**Comment by OvidiuCaba** [comment]
The link that you provided is to the dev branch. So, indeed, you accepted my pull request and you merged my changes into dev branch. The problem is that I believe you made the build based on the master branch [where you also updated the version], without merging the changes from dev into master.

As you can see, the master branch only contains the version update, but not the fix:

https://github.com/jzoss/Git-Source-Control-Provider/commits/master

And the fix is in dev:

https://github.com/jzoss/Git-Source-Control-Provider/commits/dev

"What version of tsvn do you have?"

I don't have TSVN, but Tortoise Git 2.4.0.2 and Git 2.10.2.windows.1.

**Comment by jzoss** [comment]
Yea that one comes from the dev branch.. And yes.. brain fart I ment TGit not Tsvn...

**Comment by OvidiuCaba** [comment]
> Yea that one comes from the dev branch
So the merge came from dev and the build from master? So the next step would be a merge and a new build?
I ask this because I would like to know whether I need to do something to help.

**Comment by jzoss** [comment]
Sorry it's been a while .. I moved.. July was the first part of August was really busy.. I'll keep looking..

**Comment by OvidiuCaba** [comment]
Diff works. Show Log works. Blame works. :)

So if this gets into production, this issue can be closed. Many thanks!

PS: Do not forget to test it on your machine, as well. Maybe with other setup... [different than mine: VS 2015/VS 2017 with TortoiseGit]

**Comment by jzoss** [comment]
I am going to try and finish up a few more bug before I release ..Thanks for all your help!

**Comment by OvidiuCaba** [comment]
My pleasure! :)
