### ISSUE TITLE
Diff panel should be read-only

### ISSUE THREAD

**Issue by ceztko** [jzoss/Git-Source-Control-Provider#77]
The diff panel is now editable. Since there's no currently side-effect when editing the panel (for example, the change is reflected in the source code), this should be set read-only.

**Comment by ceztko** [comment]
It seems to me that this change made the diff panel non scrollable, effectively breaking it when the changes in the file are far enough. I think a property like `IsReadOnly` should be used instead of `IsEnabled`.

**Comment by jzoss** [comment]
Opps.. that what happens when I fix bugs while in a meeting :)
