### ISSUE TITLE
Commit comment text field shouldn't allow formatting

### ISSUE THREAD

**Issue by ceztko** [jzoss/Git-Source-Control-Provider#78]
Commit comment text field is currently allowing formatting. This is quite ugly when copying from source code or copying some different font: formatting should should be disabled. See the linked image for an example:

https://www.dropbox.com/s/1a69vzp0fql90hi/commit-comment.png?dl=0

**Comment by jzoss** [comment]
Try the latest CI build. It should be fixed

**Comment by ceztko** [comment]
Fixed for me
