### ISSUE TITLE
Pending Changes Not Refreshing

### ISSUE THREAD

**Issue by NightOwl888** [jzoss/Git-Source-Control-Provider#8]
Whether waiting for the automatic refresh or manually clicking the refresh button, my changed files are not appearing in the Pending Changes window.

![norefresh](https://cloud.githubusercontent.com/assets/1538288/11451377/14d66b44-95f7-11e5-8dbe-17bf993e69dc.png)

I am using version 1.4.

Is it possible to revert to 1.3? Where can it be downloaded?

**Comment by NightOwl888** [comment]
I downloaded 1.3.5.1_Beta from the releases page, but still get the same results. No way to refresh the files and most of the time the changed files don't even show up upon loading the solution.

**Comment by jzoss** [comment]
Are the changes updating in the solution explorer? Anyway I will try and fix it tomorrow, and I can get v 1.31 out there as well.

**Comment by NightOwl888** [comment]
As you can see in the screenshot, the answer is no, Solution Explorer is not updating either (after the edit the lock icon still exists).

I have since installed the [Git Tools Extension](https://visualstudiogallery.msdn.microsoft.com/48c3e91e-d1d7-4bf9-84dd-d3b97e2d5922) which apparently is supposed to replace the Git Source Control Provider in VS2015, but unfortunately with that one I am getting an annoying "mixed line endings" message every time I edit a file. So I am still waiting for a version that is stable to use.

**Comment by jzoss** [comment]
I am preparing the 1.41 build that will fix the settings error. Question for you on this one, do you have git.exe in the path? That is if you start cmd can you type git and does it work...I'm hoping not because I think I may be close to a fix if that is the case.

**Comment by NightOwl888** [comment]
I do have the path to git.exe (directory only) in the path. In fact, I use it all of the time for pushing, pulling, merging, and rewriting history.

**Comment by jzoss** [comment]
Ok.. Not the same thing.. Can you check out the latest release 1.4.1 ? See if it fixed it.. I was able to get some of the same behavior when the plugin did not have the correct git path setup. I hope the latest update fixed it.

**Comment by scott-grove-cm** [comment]
I'm using 1.4.1 with VS 2015 Community and the Pending changes is still not refreshing

**Comment by jzoss** [comment]
@scott-grove-cm I am working on a new release to fix this.. I do not have VS 2015 Community, but I can make a VM and test it out.. Can you do me a favor.. in the releases tab there is a beta release 1.4.1.1, if yo get time can you try that and see if it fixes or mostly fixes your issues. Thanks

**Comment by scott-grove-cm** [comment]
@jzoss Just installed 1.4.1.1 and good news is I can see new and modified files now. 
If I see anything else I'll report back. Thanks :+1:

**Comment by jzoss** [comment]
@scott-grove-cm Fantastic, Glad it is working. I have a few more things to fix before I push out the next release, but I'm happy to be on the right track.. :)

**Comment by scott-grove-cm** [comment]
@jzoss Update for you - undo file changes doesn't refresh Pending Changes window. closing and re-opening doesn't work either. Only way of refreshing was to close VS and re-open

**Comment by jzoss** [comment]
@NightOwl888 and @scott-grove-cm  I have another beta release 1.4.2 Beta 1. Check it out.. From my testing .. it fixes most of the issues.. Please give it a test run, tell me what you think.
