### ISSUE TITLE
Automatically add a file to source control when it's been renamed in a project

### ISSUE THREAD

**Issue by ddobrev** [jzoss/Git-Source-Control-Provider#83]
Similar to https://github.com/jzoss/Git-Source-Control-Provider/issues/53 , a file renamed in a project - or in a solution - could be added to, or renamed in, Git as well. @jzoss what do you think?

**Comment by ddobrev** [comment]
In addition, the file with the old name can be deleted in Git. @jzoss what do you think about such a feature?

**Comment by jzoss** [comment]
It would not be bad. Din't think it would be that hard to implement.

**Comment by ddobrev** [comment]
OK, great.
I can now see I've requested the feature with two different approaches - add + delete vs rename. It makes no difference to me so please select whichever one you consider optimal.

**Comment by ddobrev** [comment]
Hello @jzoss , how have you been doing? Do you still develop this project? I can see no commits later than August. It would be a real shame if you no longer have time for it, the integration with TortoiseGit makes it much better than MS's built-in source control provider. But if you do, do you think you could start with this feature?

**Comment by jzoss** [comment]
Yeah I'm still around 😀. I moved in August and I just never caught up. I  still plan on adding new features .

**Comment by ddobrev** [comment]
I am really happy to hear it. I hope you are happy too with your new home.

**Comment by ddobrev** [comment]
@jzoss Hello again. :) How have you been, any plans to continue development? This add-in needs your brilliant work.

**Comment by jzoss** [comment]
Yeah I was starting to look at it again.. Just need to figure out what to do first. :)

**Comment by ddobrev** [comment]
Excellent, makes me really happy because after this one I have some more issues for you. :)

**Comment by jzoss** [comment]
Ok I'm back.. This will be fixed in 1.7.3 .. should also be in a pre-release in the release tab

**Comment by ddobrev** [comment]
Thank you! I am patient, I can wait for the official release. :)

**Comment by ddobrev** [comment]
By the way, does it also delete the file with the old name? If not, I guess you could still cope with just one operation, it would simply have to be Git rename instead of add.

**Comment by jzoss** [comment]
Get pumped.. v1.7.3 was just published

**Comment by ddobrev** [comment]
Works just fine. Directly renaming in Git and then displaying a single change would be a nice touch, though.
