### ISSUE TITLE
How to use this tool

### ISSUE THREAD

**Issue by tomasr78** [jzoss/Git-Source-Control-Provider#84]
I have installed this tool to VS 2017 but I don't see anywhere it. I have git installed and use default Git extension to manage it. Please explain how to use it.

**Comment by ddobrev** [comment]
Make sure you've selected "EZ-GIT" in Tools -> Options -> Source Control -> Plug-in Selection.

**Comment by jzoss** [comment]
Sorry I missed this.. my notifications got all wonkey. Please ask if you need more help
