### ISSUE TITLE
Glyphs not updated for .NET Standard projects

### ISSUE THREAD

**Issue by ddobrev** [jzoss/Git-Source-Control-Provider#86]
A typical example is a Xamarin.Forms application since the Xamarin.Forms part is a .NET Standard project. When a file is changed, its glyph in the solution explorer often remains the same. I would guess it has to do with the different project files .NET Standard uses - they can but most often do not contain their files but rather everything in their folder is shown in the solution explorer.

**Comment by jzoss** [comment]
I'll have to look at this. It works when I made a .Net Standard class library.. I'll have to check Xamarin when I get time.

**Comment by ddobrev** [comment]
@jzoss I can actually only reproduce it with just one of my projects. I guess there's something specific to that project. If I ever have the time to debug, I'll send you the results. For now I am just going to close this issue. Once again, thank you for your work.
