### ISSUE TITLE
Git bash starts with current directory env variable PWD set in lowercase

### ISSUE THREAD

**Issue by ceztko** [jzoss/Git-Source-Control-Provider#89]
When starting a git bash from Pending Changes panel, the current directory environment variable is set in lowercase. This is causing malfunctioning in some git aspects. Take for example the following directive in the `.gitconfig` file:

```
[includeIf "gitdir:D:/Repos/"]
    path = D:/Repos/gitconfig
```

If `PWD` in bash is found with lowercase directories (for example `PWD=/d/repos`), the directive is not honored. From my investigation, the culprit of the problem is `libgit2sharp` which internally normalizes some paths to lowercase, specifically `RepositoryInformation.WorkingDirectory`. Instead of fixing `libgit2sharp`, I propose to just lookup for the correct case of the path prior to launch commands with `Process` class in `BasicSccProvider`. The attached patch does exactly this.

[patch-fix-run-commands-with-case-insensitive-working-directory.txt](https://github.com/jzoss/Git-Source-Control-Provider/files/1766579/patch-fix-run-commands-with-case-insensitive-working-directory.txt)

**Comment by jzoss** [comment]
Thanks.. I will check out the patch.. If it works I'll get a new release out this weekend or early next week.

**Comment by ceztko** [comment]
Consider the patch attached here as obsolete. I was making the drive letter to lowercase as a normalization, and versions of Windows until 1709 seemed to internally further normalize it to uppercase. With Windows 1803 it seems current directory will be accepted as-is, so I preferred a default normalization to uppercase prior setting Process.StartInfo.WorkingDirectory. This is done in pull request #93

**Comment by ceztko** [comment]
For the rest pull request #93 is identical and I've tested it in these months without any issue

**Comment by jzoss** [comment]
Awesome.. I'll try to merge and test tomorrow. Hopefully I can make an
release tomorrow as well

**Comment by jzoss** [comment]
Merge and there now is a beta build you can test.. https://github.com/jzoss/Git-Source-Control-Provider/releases/tag/GSCP-CI

tell me what you think.. if I don't see any issues I will release it.
