### ISSUE TITLE
"Object reference not set to an instance of an object." when clicking the Settings button.

### ISSUE THREAD

**Issue by NightOwl888** [jzoss/Git-Source-Control-Provider#9]
The title pretty much explains it. I click settings and I get an Object reference not set to an instance of an object error from Visual Studio.

I am using version 1.4.

**Comment by jzoss** [comment]
Yep.. 1.41 has this fixed.. I was trying to one other bug before I pushed it out.

**Comment by teebee76** [comment]
I know you already fixed this, but I noticed when installing a new version of GIT that this only occurs if I use a 32bit version of GIT.  I tried installing one and then the other and back to the first again, and no error occured once the 64bit version was installed.

I also noticed that the configured values for git user.name and user.email are not filled into the text-fields on the config-page, and even if I type new values in these fields, the OK button never becomes clickable.

![image](https://cloud.githubusercontent.com/assets/5390116/11475816/9e53801c-977f-11e5-8ad9-56c0949eb28c.png)

My workaround for getting the plugin to work (get the commit/branch/bash/history clickable again) was to simply exit the Settings page by clicking refresh.

**Comment by jzoss** [comment]
Awesome  Thanks.. Very helpful.. I am just finishing up the 1.41 release .. Do you want to help me test  before I push it to the world ?

**Comment by teebee76** [comment]
Sure, I'll be glad to :) 
I am however not able to do it tonight, but will be back at work tomorrow at around 8 in the morning, can do a little uninstall reinstall of 32/64bit git and path and unpath then. Also noticed a bug in the path-settings when installing v 2.6.3 of GIT it maps to wrong directory (without (x86) on the 32-bit version, and with on the 64-bit version, so I guess there's some reverse-logic gone wrong in that version :) )
I had to fix the path manually to get it working from cmd-window. 
My last git-version was 1.8.3 so it was about time for an upgrade..
As a last comment, I haven't noticed any of the bugs reported in #8 in any of my combinations, they've all shown the padlocked/unlocked symbols correctly.

**Comment by jzoss** [comment]
Yea.. I can't recreate that yet either.. Trying to fix that.. I may do a 1.41 out just to fix the bugs that are fixed.. I wanted to fix the revert before I did that.. but that may have to wait.

**Comment by teebee76** [comment]
looks like 1.4.1 pretty much fixed all the errors I had :+1: good job 

I haven't tried uninstalling the 64bit version and reinstalling the 32bit version though

**Comment by jzoss** [comment]
I'm going to close it until I hear it is still an issue

**Comment by NightOwl888** [comment]
Sorry, I haven't had a chance to test this until now. It seems to be working fine now. No error, and I can now see my Git User Name and Git User Email, where before they were blank.
