### ISSUE TITLE
Ask to save before committing

### ISSUE THREAD

**Issue by JohanLarsson** [jzoss/Git-Source-Control-Provider#90]
I often forget to save leading to many amend commits, slight noise in history.

**Comment by JCKodelESX** [comment]
I forgot to search before ask =( But, yeah: https://github.com/jzoss/Git-Source-Control-Provider/issues/91

**Comment by jzoss** [comment]
@JohanLarsson 

So do you just want it to save, or is a modal important?

**Comment by JohanLarsson** [comment]
Just saving is fine with me, I can't think of a situation where I would answer 'no don't save but commit any way'

**Comment by jzoss** [comment]
Cool.. I'll close it.. New release coming soon

**Comment by jzoss** [comment]
@JohanLarsson and @JCKodelESX  Just letting you know.. 1.8 is out and the feature is in it.
