### ISSUE TITLE
Autosave

### ISSUE THREAD

**Issue by JCKodelESX** [jzoss/Git-Source-Control-Provider#91]
This extension is waaaaaaaaay better than the default Visual Studio git stuff, except for one small detail: it won't trigger a full solution save before operations as commit, sync, etc.

To see what I mean: create a new file, then commit your changes. The only change will be this new file, right?
Now, press Ctrl+Alt+S (or the 
![image](https://user-images.githubusercontent.com/37353100/37690324-f205f88e-2c88-11e8-9248-ea973db85c27.png) button) and try to commit again: the project file where you added the new file will be dirty.

The expected behaviour would be invoke a global save operation (so the .csproj will be written to disk) and then invoke the tortoise commit dialog (that should mark both as change).

**Comment by jzoss** [comment]
Coming very soon .. 
![image](https://user-images.githubusercontent.com/3586254/39884774-8eb4b1cc-5450-11e8-80c8-750c73a07df2.png)

**Comment by jzoss** [comment]
Done in 1.74.. Which will be released soon.. 
@JCKodelESX 
If you could help .. get the latest CI build and test it out https://github.com/jzoss/Git-Source-Control-Provider/releases/tag/GSCP-CI
