### ISSUE TITLE
Git Source Control Provider Not appearing in VS2015 Search

### ISSUE THREAD

**Issue by wescrockett** [jzoss/Git-Source-Control-Provider#95]
When searching for 'Git Source Control Provider' in Visual Studio Gallery (online), no matching results are found. Plenty of others are, but per the instructions for installation, not 'Git Source Control Provider'

**Comment by wescrockett** [comment]
CANCEL THIS... I am using SSDT 2015 for SSIS development... Version Control functions aren't installed for it.

**Comment by jzoss** [comment]
Ok. It might not be to hard to let the extension install in SSDT.. I can take a look a bit later.

**Comment by wescrockett** [comment]
That would be phenomenal. Thank you.

**Comment by jzoss** [comment]
@wescrockett Do me a favor.. I don't have the right VM setup to test SSDT yet, but I have attached a special build.. if you run it can you tell me if it says it can install or not? If it does install.. tell me if it works or crashes .. Thanks
[GitSccProvider.zip](https://github.com/jzoss/Git-Source-Control-Provider/files/2005733/GitSccProvider.zip)

**Comment by wescrockett** [comment]
when I get back to my desk, I will try it.

**Comment by wescrockett** [comment]
Installed fine, but would not load when going to Options > Source Control
and selecting EZ-Git:

[image: EZGitError.PNG]
  <entry>
    <record>260</record>
    <time>2018/05/15 16:58:14.067</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [BasicSccProvider]</description>
    <guid>{C4128D99-2000-41D1-A6C3-704E6C1A3DE2}</guid>
  </entry>
  <entry>
    <record>261</record>
    <time>2018/05/15 16:58:14.067</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>CreateInstance failed for package
[BasicSccProvider]Source: &apos;mscorlib&apos; Description: Could not load
file or assembly &apos;Microsoft.VisualStudio.Shell.15.0, Version=15.0.0.0,
Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its
dependencies. The system cannot find the file
specified.&#x000D;&#x000A;System.IO.FileNotFoundException: Could not load
file or assembly &apos;Microsoft.VisualStudio.Shell.15.0, Version=15.0.0.0,
Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its
dependencies. The system cannot find the file
specified.&#x000D;&#x000A;File name:
&apos;Microsoft.VisualStudio.Shell.15.0, Version=15.0.0.0, Culture=neutral,
PublicKeyToken=b03f5f7f11d50a3a&apos;&#x000D;&#x000A;   at
System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String
name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack
type)&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.GetType(String
name, Boolean throwOnError, Boolean ignoreCase)&#x000D;&#x000A;   at
System.Activator.CreateInstanceFromInternal(String assemblyFile, String
typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder,
Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence
securityInfo)&#x000D;&#x000A;   at
System.AppDomain.CreateInstanceFrom(String assemblyFile, String
typeName)&#x000D;&#x000A;&#x000D;&#x000A;WRN: Assembly binding logging is
turned OFF.&#x000D;&#x000A;To enable assembly bind failure logging, set the
registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to
1.&#x000D;&#x000A;Note: There is some performance penalty associated with
assembly bind failure logging.&#x000D;&#x000A;To turn this feature off,
remove the registry value
[HKLM\Software\Microsoft\Fusion!EnableLog].&#x000D;&#x000A;</description>
    <guid>{C4128D99-2000-41D1-A6C3-704E6C1A3DE2}</guid>
    <hr>80004005 - E_FAIL</hr>
    <errorinfo></errorinfo>
  </entry>

**Comment by wescrockett** [comment]
I'm running SSDT 2015, but I don't believe there are any updates currently for it. It is Visual Studio 2015 Shell.

**Comment by jzoss** [comment]
@wescrockett  So.. I broke 2015 in that last build it looks like.. here is a new one for you to test.. https://github.com/jzoss/Git-Source-Control-Provider/releases/download/GSCP-CI/GitSccProvider.vsix

**Comment by wescrockett** [comment]
New Error:

`  <entry>
    <record>268</record>
    <time>2018/05/15 21:02:23.200</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [BasicSccProvider]Source: &apos;GitSccProvider&apos; Description: Object reference not set to an instance of an object.&#x000D;&#x000A;System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at GitScc.BasicSccProvider.SetupStatusMenu()&#x000D;&#x000A;   at GitScc.BasicSccProvider.&lt;InitializeAsync&gt;d__8.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass16_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Threading.ThreadingTools.&lt;WithCancellationSlow&gt;d__10.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Threading.JoinableTask.&lt;JoinAsync&gt;d__76.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()&#x000D;&#x000A;   at Microsoft.VisualStudio.Threading.JoinableTask.Join(CancellationToken cancellationToken)&#x000D;&#x000A;   at Microsoft.VisualStudio.Threading.JoinableTask`1.Join(CancellationToken cancellationToken)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.VsTaskLibraryHelper.&lt;&gt;c__DisplayClass24_1`1.&lt;AsVsTask&gt;b__2()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.GetResult()</description>
    <guid>{C4128D99-2000-41D1-A6C3-704E6C1A3DE2}</guid>
    <hr>80004003 - E_POINTER</hr>
    <errorinfo></errorinfo>
  </entry>
  <entry>
    <record>269</record>
    <time>2018/05/15 21:02:23.215</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [BasicSccProvider]</description>
    <guid>{C4128D99-2000-41D1-A6C3-704E6C1A3DE2}</guid>
    <hr>80004003 - E_POINTER</hr>
    <errorinfo></errorinfo>
  </entry>`

**Comment by jzoss** [comment]
Actually that's not a bad amount of progress.. Considering I don't have a VM yet.. Hmm..I may have an idea. 


Anyway Try this.. 
[GitSccProvider.zip](https://github.com/jzoss/Git-Source-Control-Provider/files/2009786/GitSccProvider.zip)

**Comment by wescrockett** [comment]
Looks like it worked?

[image: image.png]

**Comment by wescrockett** [comment]
Seems to be.[image: Capture.PNG]

**Comment by jzoss** [comment]
@wescrockett just wanted to let you know, the 1.8 release is out and it should appear in the extension manager now.

**Comment by wescrockett** [comment]
Awesome! I'll check it out. Thanks!
