### ISSUE TITLE
Cannot push upgrade until Package is upgraded to Async Package.. 

### ISSUE THREAD

**Issue by jzoss** [jzoss/Git-Source-Control-Provider#96]

**Comment by jzoss** [comment]
Hi people..  (I'll pick on these people because you have helped me before @JCKodelESX @ceztko @ddobrev @PureKrome @teebee76)

I am in need of help.. So I went to push an update and I got a nasty surprise.  

![image](https://user-images.githubusercontent.com/3586254/39896421-a744baca-5473-11e8-98f1-d660fbbd9c7e.png)

Basically, they are forcing me to update from synchronous extension to an asynchronous. Now I kinda sorta heard about it maybe.. and I thought that is not a bad thing to do, but I had not idea it was coming. I figured I should be careful with doing something like that because it's all about threading and threading bugs are a pain. Anyway, problem is I can't even do a minor patch release now. 

So I ignored what I was suppose to be doing for a while and did the upgrade.. It was not super hard, but not the most fun I've had either. 

So what help I could really use right now, is just people to test it. I have .. and it no longer crashes visual studio :) Anyway if I could get a few people to help me test it I'd be way more comfortable releasing it..   

it can be found 
![image](https://user-images.githubusercontent.com/3586254/39896617-70e4ca82-5474-11e8-97fd-8967f5c86b51.png)

**Comment by PureKrome** [comment]
🤚 I'll test it out! Downloading it now...

**Comment by ddobrev** [comment]
Just installed. I'll send my feedback tonight.

**Comment by jzoss** [comment]
Cool people.. Any initial feedback so far.. It seems fine to me so far..

**Comment by ddobrev** [comment]
@jzoss I apologize. I forgot about this because nothing's happened since I installed the preview.

**Comment by jzoss** [comment]
@ddobrev well that's good news. :)

**Comment by PureKrome** [comment]
@jzoss been using it since I installed it 4 days ago, plenty of times. No crashes etc. "Just Works". 👍

**Comment by jzoss** [comment]
So.. Apparently in my rush to fix things.. I kinda made it not work in Visual Studio 2015.. For a few minutes .. I kinda thought about just cutting off support for 2015.. but alas I went and fixed it. It involved changing around some dependencies .. anyway I figure you all must be using 2017, but if you could get the latest test build here https://github.com/jzoss/Git-Source-Control-Provider/releases/download/GSCP-CI/GitSccProvider.vsix

and keep testing that would be sweet.

**Comment by ddobrev** [comment]
@jzoss installed last night, nothing's happened so far.

**Comment by jzoss** [comment]
Hi all again.. So I had to update a few more references here and there.. and then my visual studio died and I have that fun.. Anyway.. if you coudl try https://github.com/jzoss/Git-Source-Control-Provider/releases/download/GSCP-CI/GitSccProvider.vsix .. It is my plan for this to be the last pre-release build. Hopefully I'll just update the version number and release.. 

Again thanks @ddobrev and @PureKrome for your help!.. 

@PureKrome did you notice the comment counter?

**Comment by ddobrev** [comment]
@jzoss just installed.

**Comment by PureKrome** [comment]
Just installed latest one (link above). Also loving the character count :)

for those that don't know what @jzoss  and I are talking about ....

![image](https://user-images.githubusercontent.com/899878/40338047-5bd0a184-5db6-11e8-81c8-4a17bc40cdf6.png)

Also - no problems so far with previous versions installed in the last week/fortnight.

**Comment by jzoss** [comment]
Thanks everyone.. Just pushed the 1.8 release!
